import './style.css';import * as T from 'three';import R from '@dimforge/rapier3d-compat';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import richieUrl from './assets/richie.glb?url';import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';import {registerSW} from 'virtual:pwa-register';import {Robot} from './robots';import {Walker,seatedAudience,cheeringCrowd,rng} from './people';import {G,DT,zones,stats,ballistic,type Stats} from './core';
declare const __APP_VERSION__:string;
registerSW({immediate:true});
await R.init();
const app=document.querySelector('#app')!,canvas=document.createElement('canvas');app.append(canvas);
app.insertAdjacentHTML('beforeend',`<section id="title" class="screen"><div><span class="tag">DEVOXX BELGIUM · ROBOT GAMES</span><h1>PLEASE<br>DO NOT<br><em>THROW</em><br>RICHIE.</h1><p class="sub">AN IRRESPONSIBLE DEVOXX PHYSICS GAME</p><p class="copy">Richie has a keynote. Richie has no legs.<br>Gravity is about to become a team sport.</p><p id="touchNote" class="tnote" hidden>Touch controls are on: the stick aims, hold <b>HOP</b> to charge and let go to jump, <b>E</b> asks a robot for help, <b>R</b> resets. Landscape works best.</p><button id="start" class="btn">LET’S MAKE THIS WORSE ↗</button><button id="playground" class="btn alt">PHYSICS PLAYGROUND</button></div></section>
<div id="hud" class="hud" hidden><div class="top"><div><div class="brand">PLEASE DO NOT THROW RICHIE.</div><div id="zone" class="zone"></div></div><div class="timer"><small>KEYNOTE STARTS IN</small><span id="time">10:00</span><div id="tokens" class="zone">0 / 8 TOKENS</div></div></div><div id="toast" class="toast"></div><div id="hint" class="hint">SPACE TO HOP</div><div class="controls"><kbd>WASD</kbd> aim · <kbd>SPACE</kbd> charge/hop · <kbd>E</kbd> assist · <kbd>R</kbd> reset · drag camera</div><div class="charge"><span>QUESTIONABLE POTENTIAL</span><div><i id="bar"></i></div></div></div>
<div id="cinema" class="cinema" hidden><span id="cinemaText"></span><small>SPACE · ENTER · TAP TO SKIP</small><button id="skip" class="skipbtn">SKIP ▸</button></div>
<div id="results" class="modal" hidden><div class="panel"><span class="tag">AGAINST ALL REASONABLE EXPECTATIONS</span><h2>KEYNOTE READY.</h2><div id="stats" class="stats"></div><button id="again" class="btn">ONE MORE BAD IDEA ↗</button></div></div>
<div id="touch" class="touch-ui" hidden><div id="stick" class="stick"><i id="stickKnob"></i></div><div class="tbtns"><button id="tE">E<br>ASSIST</button><button id="tHop">HOP</button><button id="tR">R<br>RESET</button></div></div>
<div class="version">v${__APP_VERSION__}</div>`);
const el=(id:string)=>document.getElementById(id)!;const renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new T.Scene();scene.background=new T.Color(0x142b3b);scene.fog=new T.Fog(0x142b3b,45,110);const camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.1,350);
// An environment map is what makes plastic shells and glass lenses read as materials at all.
const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.55;pmrem.dispose();
scene.add(new T.HemisphereLight(0xd8ecf2,0x3d4654,2.5));const sun=new T.DirectionalLight(0xffe1bd,3);sun.position.set(-10,20,-10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=sun.shadow.camera.bottom=-26;sun.shadow.camera.right=sun.shadow.camera.top=26;sun.shadow.camera.near=1;sun.shadow.camera.far=90;sun.shadow.bias=-.0006;sun.shadow.normalBias=.03;scene.add(sun,sun.target);
const world=new R.World({x:0,y:-G,z:0});world.timestep=DT;const mat=(c:T.ColorRepresentation,m=0)=>new T.MeshStandardMaterial({color:c,roughness:.65,metalness:m});
const solids:T.Mesh[]=[];function box(x:number,y:number,z:number,w:number,h:number,d:number,c:T.ColorRepresentation,physical=true){const q=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));q.position.set(x,y,z);q.castShadow=q.receiveShadow=true;scene.add(q);solids.push(q);if(physical)world.createCollider(R.ColliderDesc.cuboid(w/2,h/2,d/2).setTranslation(x,y,z).setFriction(.85));return q}
function cyl(x:number,y:number,z:number,r:number,h:number,c:T.ColorRepresentation,parent: T.Object3D=scene){const q=new T.Mesh(new T.CylinderGeometry(r,r,h,16),mat(c));q.position.set(x,y,z);q.castShadow=true;parent.add(q);return q}
function sph(x:number,y:number,z:number,r:number,c:T.ColorRepresentation,parent:T.Object3D=scene,sx=1,sy=1,sz=1){const q=new T.Mesh(new T.SphereGeometry(r,20,14),mat(c));q.position.set(x,y,z);q.scale.set(sx,sy,sz);q.castShadow=true;parent.add(q);return q}
function label(text:string,x:number,y:number,z:number,w=7,bg='#17303d',faceBack=false){const c=document.createElement('canvas');c.width=1024;c.height=220;const g=c.getContext('2d')!;g.fillStyle=bg;g.fillRect(0,0,1024,220);g.fillStyle='#f8e9c9';g.font='bold 65px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(text,512,110,960);const q=new T.Mesh(new T.PlaneGeometry(w,w*.215),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),side:T.DoubleSide}));q.position.set(x,y,z);q.rotation.y=faceBack?0:Math.PI;scene.add(q);return q}
function floor(a:number,b:number,y:number,w=22,c=0x70838a){box(0,y-.5,(a+b)/2,w,1,b-a,c);for(const x of [-w/2,w/2])box(x,y+1,(a+b)/2,.25,2,b-a,0x284451)}
const player=world.createRigidBody(R.RigidBodyDesc.dynamic().setTranslation(0,.8,4).setLinearDamping(.18).setAngularDamping(1.2).setCcdEnabled(true));const pc=world.createCollider(R.ColliderDesc.cuboid(.3,.44,.3).setMass(1.2).setFriction(.9).setRestitution(.23),player);
// Richie is the official Reachy Mini geometry (scripts/build-richie.py), 3.5x life size so a
// 28 cm robot reads at game scale. The GLB's base sits at y=0; the rigid body's origin is
// the collider centre, so the model hangs 0.44 below it. Antennas and head are separate
// nodes pivoted on the real joints.
const richie=new T.Group();scene.add(richie);const richieModel=(await new GLTFLoader().loadAsync(richieUrl)).scene;richieModel.scale.setScalar(3.5);richieModel.position.y=-.44;richieModel.traverse(o=>{const m=o as T.Mesh;if(!m.isMesh)return;m.castShadow=true;const src=m.material as T.MeshStandardMaterial,c=src.color,shell=c.r>.8;m.material=src.transparent?new T.MeshPhysicalMaterial({color:0x9fc4d8,roughness:.05,metalness:.1,transparent:true,opacity:.5,depthWrite:false}):new T.MeshPhysicalMaterial({color:c,roughness:shell?.32:.45,metalness:shell?0:.4,clearcoat:shell?.7:.15,clearcoatRoughness:.25})});richie.add(richieModel);
const antennaL=richieModel.getObjectByName('antenna_left')!,antennaR=richieModel.getObjectByName('antenna_right')!,richieHead=richieModel.getObjectByName('head')!;
// Continuous venue: registration, exhibition, gap, stairs, upper foyer, corridor, auditorium, stage.
floor(-12,66,0);floor(81,90,0);floor(114,136,6);floor(147,186,13,24,0x495661);floor(241,270,6.4,26,0x273b49);
label('KINEPOLIS · DEVOXX',0,7,-7,14,'#17303d',true);
// Ground floor: the entrance stairs at the bottom of the plan, reception, the BOF rooms and the exhibition hall.
for(let i=0;i<3;i++)box(0,-(i+1)*.35+.17,-5-i*1.2,14,.35,1.2,0x5e6f77);label('ENTRANCE',0,2.4,-9,5,'#17303d',true);
box(-7,1.2,14,6,2.4,2,0xe5ddca);label('RECEPTION · REGISTRATION',-7,1.5,12.9,5.6,'#e5ddca');
for(const [s,n] of [[-1,'BOF 1'],[1,'BOF 2'],[-1,'BOF 3'],[1,'BOF 4']] as const){const z=n.endsWith('1')||n.endsWith('2')?18:26;box(s*10.7,1.3,z,.4,2.6,2.2,0x1d2f3a,false);label(n,s*10.45,2.9,z,2.2,'#22323b')}label('EXHIBITION HALL',0,5.5,30,10);
for(let z=8;z<27;z+=5)for(const x of [-3,3]){cyl(x,.7,z,.08,1.4,0xaab8ba);box(x,.8,z+2,.08,.12,4,0x24343e)}
for(let z=34;z<59;z+=9)for(const s of [-1,1]){box(s*8,1,z,4,2,3,s>0?0x315b6b:0x744955);label(z%2?'ROBOT LAB':'DEVOXX',s*8,3.2,z-1.55,3.8)}
label('KEYNOTE ↑',0,5.3,59,7);const voxxy=new Robot('voxxy').place(-2,0,63,Math.PI).patrol([[-2,0,63],[3,0,60.5],[5.5,0,64],[-4.5,0,65]]);scene.add(voxxy.group);
for(let i=0;i<24;i++){const h=(i+1)*.25;box(0,h/2,90+i+.5,14,h,1,0x718089)}
// Escalators flank the grand staircase up to the cinema level: a ramp collider each, with handrails.
for(const s of [-1,1]){const q=new T.Mesh(new T.BoxGeometry(2.6,.3,24.8),mat(0x3f4d56));q.position.set(s*8.4,3.1,102);q.rotation.x=-Math.atan2(6,24);q.receiveShadow=true;scene.add(q);world.createCollider(R.ColliderDesc.cuboid(1.3,.15,12.4).setTranslation(s*8.4,3.1,102).setRotation({x:Math.sin(-Math.atan2(6,24)/2),y:0,z:0,w:Math.cos(-Math.atan2(6,24)/2)}).setFriction(.3));for(const r of [-1.2,1.2]){const h=new T.Mesh(new T.BoxGeometry(.08,1,24.8),mat(0x9fb0b8,.6));h.position.set(s*8.4+r,4.0,102);h.rotation.x=-Math.atan2(6,24);scene.add(h)}label('ESCALATOR',s*8.4,7.6,114.6,2.6)}label('GRAND STAIRCASE',0,7.2,89.4,7);
label('FOYER · CINEMA LEVEL',0,10,117,10);const biggy=new Robot('biggy').place(0,6,121,Math.PI).patrol([[0,6,121],[-4,6,124],[3,6,127],[4.5,6,120]]);scene.add(biggy.group);label('HEAVY ASSISTANCE',-5,9,127,6);box(8,6.6,130,4,1.2,1.4,0x8a6a4a);label('FOYER BAR',8,8.2,129.2,3.4,'#4a3a2a');
box(0,9.3,146,24,7.4,1,0x304a58);
// The corridor between the auditoriums: rooms 1-14 on the plan, 8 is where the keynote is.
for(let i=0;i<14;i++){const n=i+1;if(n===8)continue;const s=n<8?-1:1,z=150+(n<8?n-1:n-8)*5.2;box(s*11.7,14.3,z,.4,2.6,2.4,0x1a2830,false);label('AUDITORIUM '+n,s*11.45,16.1,z,2.6,'#1f2f38')}
const minis:Robot[]=[];for(let i=0;i<4;i++){const z=154+i*7,x=(i%2?1:-1)*8.5;const rb=new Robot(i%2?'droid':'voxxy',.55).place(x,13,z,(i%2?1:-1)*Math.PI/2).patrol([[x,13,z],[x,13,z+3],[x*.7,13,z+1.5]]);scene.add(rb.group);minis.push(rb)}
label('AUDITORIUM 8 · KEYNOTE',0,17,184,11);
// Auditorium 8 the Kinepolis way: you come in at the top and the room rakes down to the
// screen — twelve stepped tiers of gently curved seat rows, an aisle either side of the
// centre block, the front three tiers standing room tonight, then the stage.
const ROWS=12,ROW_D=4.6,Z0=186,rowY=(i:number)=>13-i*.6;
const seatGeo:T.BufferGeometry[]=[],seatSpots:{x:number,y:number,z:number}[]=[],crowdSpots:{x:number,y:number,z:number}[]=[];
for(let i=0;i<ROWS;i++){const y=rowY(i),z=Z0+i*ROW_D+ROW_D/2;box(0,y/2,z,26,y,ROW_D,i%2?0x3d4d59:0x435460);for(const s of [-1,1])box(s*13.2,y+1.5,z,.4,3,ROW_D,0x1d2f3a);
 if(i>=9){for(let c=-6;c<=6;c++)crowdSpots.push({x:c*1.3+(i%2?.55:0),y,z:z-1.3+(c%2?1.8:0)});continue}
 for(let c=-9;c<=9;c++){const x=c*1.2;if(Math.abs(c)===4||(i===4&&Math.abs(x)<1.3))continue;const zz=z+x*x*.012;
  const base=new T.BoxGeometry(1.08,.5,1.05);base.translate(x,y+.25,zz);const back=new T.BoxGeometry(1.08,.75,.22);back.translate(x,y+.62,zz+.45);seatGeo.push(base,back);seatSpots.push({x,y:y+.5,z:zz-.02})}
 for(const [bx,hw] of [[0,4.1],[-8.4,2.95],[8.4,2.95]])world.createCollider(R.ColliderDesc.cuboid(hw,.28,.55).setTranslation(bx,y+.28,z+bx*bx*.012).setFriction(.8))}
const seats=new T.Mesh(mergeGeometries(seatGeo,false)!,new T.MeshStandardMaterial({color:0x8a2f2b,roughness:.9}));seats.castShadow=seats.receiveShadow=true;scene.add(seats);
scene.add(seatedAudience(seatSpots));const crowdM=cheeringCrowd(crowdSpots);scene.add(crowdM.group);let crowdEx=0;
const droid=new Robot('droid').place(-4.7,rowY(4),206,Math.PI*.6).patrol([[-4.7,rowY(4),205],[-4.7,rowY(4),208.4]]);scene.add(droid.group);box(0,rowY(4)+.4,207,1.7,.8,1.4,0xb4493d);label('RECLINE',0,rowY(4)+1.4,207.9,1.6,'#5a2a26');
box(0,6.65,256,20,.5,16,0x1b2a35);box(3,7.55,258,.9,1.3,.7,0x2a3d4a);box(0,12.4,269,26,11,.5,0x0f202b);label('DEVOXX · KEYNOTE READY',0,12.4,268.6,18);const spots=[-8,8].map(x=>{const s=new T.SpotLight(0xffd29b,0,40,Math.PI/5,.7);s.position.set(x,17,252);s.target.position.set(0,7,256);scene.add(s,s.target);return s});
const tokenPos=[[5,1,21],[-5,1,43],[4,1,84],[-7,4,103],[5,7,125],[-7,14,170],[7,12.4,200],[0,8.4,236]],tokens:T.Mesh[]=[];for(const [x,y,z] of tokenPos){const q=new T.Mesh(new T.OctahedronGeometry(.35),mat(0xffc64e,.6));q.position.set(x,y,z);scene.add(q);tokens.push(q)}
const keys=new Set<string>(),press=new Set<string>(),release=new Set<string>();addEventListener('keydown',e=>{if(!keys.has(e.code))press.add(e.code);keys.add(e.code);if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>{keys.delete(e.code);release.add(e.code)});let drag=false,yaw=0,pitch=.42,dist=8,lastPX=0,lastPY=0;canvas.onpointerdown=e=>{drag=true;lastPX=e.clientX;lastPY=e.clientY};canvas.onpointerup=canvas.onpointercancel=()=>drag=false;canvas.onpointermove=e=>{if(!drag)return;const mx=e.clientX-lastPX,my=e.clientY-lastPY;lastPX=e.clientX;lastPY=e.clientY;yaw-=mx*.004;pitch=T.MathUtils.clamp(pitch+my*.003,.15,1.1)};
// Touch: a stick feeds the same aim vector WASD does, and the buttons press the same keys.
const stick={x:0,y:0},touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
if(touch){document.body.classList.add('touch');el('touch').hidden=false;el('touchNote').hidden=false;const st=el('stick'),knob=el('stickKnob');let sid=-1;const moveStick=(e:PointerEvent)=>{const r=st.getBoundingClientRect(),R=r.width/2-8,dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),l=Math.hypot(dx,dy),k=l?Math.min(l,R)/l:0;stick.x=dx*k/R;stick.y=dy*k/R;knob.style.transform=`translate(${dx*k}px,${dy*k}px)`};st.onpointerdown=e=>{sid=e.pointerId;moveStick(e);try{st.setPointerCapture(sid)}catch{}};st.onpointermove=e=>{if(e.pointerId===sid)moveStick(e)};st.onpointerup=st.onpointercancel=e=>{if(e.pointerId===sid){sid=-1;stick.x=stick.y=0;knob.style.transform=''}};
 const bind=(id:string,code:string)=>{const b=el(id);b.onpointerdown=e=>{e.preventDefault();b.classList.add('down');if(!keys.has(code))press.add(code);keys.add(code);try{b.setPointerCapture(e.pointerId)}catch{}};const up=()=>{b.classList.remove('down');if(keys.has(code)){keys.delete(code);release.add(code)}};b.onpointerup=b.onpointercancel=up;b.oncontextmenu=e=>e.preventDefault()};bind('tHop','Space');bind('tE','KeyE');bind('tR','KeyR')}canvas.onwheel=e=>dist=T.MathUtils.clamp(dist+e.deltaY*.008,4,16);
let audio:AudioContext|null=null;function tone(a:number,b:number,d=.16,type:OscillatorType='sine'){audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type=type;o.frequency.setValueAtTime(a,t);o.frequency.exponentialRampToValueAtTime(b,t+d);g.gain.setValueAtTime(.12,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(audio.destination);o.start();o.stop(t+d)}
let wobble=0,lastVy=0,freeLook:{pos:T.Vector3,at:T.Vector3}|null=null,skipReq=false,biggyBusyT=0;const robots=[voxxy,biggy,droid,...minis];
// The crowd: people wandering the exhibition hall, the foyer and the corridor, each on a
// private loop of waypoints so no two walk the same beat.
const area=(seed:number,n:number,x0:number,x1:number,z0:number,z1:number,y:number,ok:(x:number,z:number)=>boolean=()=>true)=>{const r=rng(seed),pts:T.Vector3[]=[];while(pts.length<n){const x=x0+r()*(x1-x0),z=z0+r()*(z1-z0);if(ok(x,z))pts.push(new T.Vector3(x,y,z))}return pts};
const hallOk=(x:number,z:number)=>!(Math.abs(Math.abs(x)-8)<3&&[34,43,52].some(bz=>Math.abs(z-bz)<2.6))&&!(Math.abs(x+7)<3.6&&Math.abs(z-14)<1.8)&&!(Math.abs(x)<3.4&&z>7&&z<27&&Math.abs(Math.abs(x)-3)<.5);
const walkers:Walker[]=[];for(let i=0;i<26;i++)walkers.push(new Walker(100+i,area(100+i,5,-9.5,9.5,6,58,0,hallOk)));for(let i=0;i<8;i++)walkers.push(new Walker(200+i,area(200+i,4,-9,9,116,134,6,(x,z)=>!(x>5.5&&Math.abs(z-130)<1.5))));for(let i=0;i<10;i++)walkers.push(new Walker(300+i,area(300+i,4,-9,9,150,183,13)));walkers.forEach(w=>scene.add(w.group));
let state:'title'|'cinematic'|'play'|'end'|'results'='title',playground=false,st:Stats=stats(),cp=0,charge=0,ground=false,mode:'richie'|'voxxy'|'biggy'='richie',helperCharge=0,reclines=0,crowd=0,coins=0,toastT=0,cine=0,endT=0,prevVy=0,tumble=0;
const say=(s:string,t=1.4)=>{el('toast').textContent=s;toastT=t};function reset(){const q=zones[cp];player.setTranslation({x:q[1],y:q[2]+.8,z:q[3]},true);player.setLinvel({x:0,y:0,z:0},true);player.setAngvel({x:0,y:0,z:0},true);player.setRotation({x:0,y:0,z:0,w:1},true);mode='richie';helperCharge=0;charge=0}
function play(){state='play';freeLook=null;el('title').hidden=true;el('cinema').hidden=true;el('results').hidden=true;el('hud').hidden=false}
function start(){st=stats();cp=0;coins=0;tokens.forEach(x=>x.visible=true);reset();el('title').hidden=true;el('hud').hidden=true;if(playground){play()}else{state='cinematic';el('cinema').hidden=false;cine=0}}
function showResults(){state='results';el('hud').hidden=true;el('results').hidden=false;el('stats').innerHTML=[['TIME',fmt(st.time)],['HOPS',st.hops],['FACEPLANTS',st.faceplants],['VOXXY THROWS',st.throws],['BIGGY IMPACTS',st.impacts],['UNINTENDED STAIR DESCENTS',st.stairs],['COFFEES DESTROYED',st.coffees],['CROISSANTS DESTROYED',st.croissants],['TOKENS',coins+'/8'],['DEVELOPERS INJURED','0*']].map(x=>'<span>'+x[0]+'</span><b>'+x[1]+'</b>').join('')}
el('skip').onclick=()=>{skipReq=true};el('cinema').onpointerdown=()=>{skipReq=true};el('start').onclick=start;el('again').onclick=()=>{el('results').hidden=true;start()};el('playground').onclick=()=>{playground=true;start()};
function step(dt:number){const p=player.translation(),v=player.linvel();const hit=world.castRay(new R.Ray(p,{x:0,y:-1,z:0}),.7,true,undefined,undefined,pc,player);const was=ground;ground=!!hit&&v.y<1.5;const q=new T.Quaternion().copy(player.rotation()),up=new T.Vector3(0,1,0).applyQuaternion(q);const pv=new T.Vector3(p.x,p.y,p.z);if(ground&&!was&&Math.abs(prevVy)>4){if(up.y<.65)st.faceplants++;say(Math.abs(prevVy)>12?'RICHIE DISAGREES':'BONK',.7);robots.forEach(rb=>{if(rb.position.distanceTo(pv)<9)rb.react()})}if(ground&&up.y<.96){tumble+=dt;if(tumble>1){player.setRotation(q.slerp(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),yaw),dt*8),true);player.setAngvel({x:0,y:0,z:0},true)}}else tumble=0;
 const f=new T.Vector3(-Math.sin(yaw),0,Math.cos(yaw)),r=new T.Vector3(-Math.cos(yaw),0,-Math.sin(yaw));const dir=f.multiplyScalar((keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-stick.y).add(r.multiplyScalar((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+stick.x)).clampLength(0,1);
 if(press.has('KeyR')){reset();say('RETRY-DRIVEN DEVELOPMENT')}if(mode==='richie'){if(keys.has('Space')&&ground)charge=Math.min(1,charge+dt);if(release.has('Space')&&ground){const c=Math.max(.08,charge);player.setLinvel({x:dir.x*(2.5+c*5),y:4.5+c*5.5,z:dir.z*(2.5+c*5)},true);player.setAngvel({x:dir.z*1.5,y:.2,z:-dir.x*1.5},true);st.hops++;tone(180,580);charge=0}if(!ground&&dir.lengthSq())player.applyImpulse({x:dir.x*dt,z:dir.z*dt,y:0},true)}
 if(press.has('KeyE')){if(mode!=='richie'){mode='richie'}else if(p.z>57&&p.z<68){mode='voxxy';voxxy.busy=true;player.setGravityScale(0,true);say('VOXXY CAN HELP')}else if(p.z>118&&p.z<136){mode='biggy';biggy.busy=true;biggy.place(0,6,127,0);helperCharge=0;player.setTranslation({x:0,y:7,z:132},true);say('HIT RICHIE VERY HARD')}else if(Math.abs(p.z-207)<5){reclines++;say(reclines%3?'RECLINE. …NOTHING.':'EJECT MODE');droid.react();if(reclines%3===0)player.setLinvel(ballistic(p,{x:0,y:rowY(7)+1,z:221},1.45),true)}}
 if(mode==='voxxy'){const vp=voxxy.position;player.setTranslation({x:vp.x,y:vp.y+2.3,z:vp.z},true);player.setLinvel({x:0,y:0,z:0},true);if(keys.has('Space'))helperCharge=Math.min(1,helperCharge+dt);if(release.has('Space')){player.setGravityScale(1,true);voxxy.busy=false;voxxy.react();player.setLinvel(ballistic(player.translation(),{x:dir.x*4,y:1,z:85+helperCharge*2},1.55),true);mode='richie';st.throws++;tone(140,700,.45,'sawtooth');say('THE TITLE WAS A SUGGESTION');helperCharge=0}}
 if(mode==='biggy'){if(keys.has('Space')){helperCharge=Math.min(1,helperCharge+dt);biggy.place(0,6,127-helperCharge*4,0)}if(release.has('Space')){biggy.place(0,6,130.6,0);biggy.react();biggyBusyT=1.5;player.setLinvel(ballistic(p,{x:dir.x*5,y:14,z:152+helperCharge*4},1.8),true);st.impacts++;mode='richie';tone(85,22,.6,'sawtooth');say(helperCharge>.8?'ORBIT ACHIEVED':'THIS SEEMS UNSAFE');helperCharge=0}}
 world.step();prevVy=v.y;const np=player.translation();for(let i=cp+1;i<zones.length;i++){const z=zones[i];if(np.z>=z[3]&&np.y>=z[2]-.5){cp=i;say('CHECKPOINT · '+z[0])}}tokens.forEach((x,i)=>{x.rotation.y+=dt*2;if(x.visible&&x.position.distanceTo(new T.Vector3().copy(np))<1.2){x.visible=false;coins++;say('EXTREMELY NECESSARY TOKEN')}});if(np.z>226&&np.y<12&&np.y>5.5&&crowd<3){const target=crowd===2?{x:0,y:8.6,z:256}:{x:(crowd%2?1:-1)*1.5,y:crowd?8:rowY(10)+1.6,z:233+crowd*8};player.setLinvel(ballistic(np,target,crowd===2?2:1.3),true);crowd++;crowdEx=1;say(crowd===3?'ONE LAST BAD IDEA':'AUDIENCE PARTICIPATION')}if(np.z>250&&np.y<10&&crowd===3){state='end';crowdEx=2;endT=0;say('WHAM');spots.forEach(s=>s.intensity=80)}if(np.y<(cp>4?4.5:-8)||Math.abs(np.x)>25)reset();st.time+=dt}
let last=performance.now(),acc=0,frames=0;function loop(now:number){requestAnimationFrame(loop);const d=Math.min(.2,(now-last)/1000);last=now;if(state==='play'||state==='end'){acc+=d;let n=0;while(acc>=DT&&n++<12){step(DT);acc-=DT}}const p=new T.Vector3().copy(player.translation());richie.position.copy(p);richie.quaternion.copy(player.rotation());sun.target.position.copy(p);
 // The venue lives whatever the state: robots patrol, people wander, the front rows bounce.
 const tt=now*.001;robots.forEach(rb=>rb.update(d,tt,p));walkers.forEach(w=>w.update(d,tt));crowdM.update(tt,crowdEx);crowdEx=Math.max(0,crowdEx-d*.4);if(biggyBusyT>0){biggyBusyT-=d;if(biggyBusyT<=0)biggy.busy=false}
 // Antennas are springs: a landing or launch sets them ringing, and the finale is a celebration.
 const vy=player.linvel().y;wobble=Math.min(1.2,wobble*Math.pow(.15,d)+Math.abs(vy-lastVy)*.08);lastVy=vy;const t=now*.001,ring=(state==='end'||state==='results'?.55*Math.sin(t*9):Math.sin(t*16)*wobble)+(state==='title'?Math.sin(t*2.2)*.1:0);antennaL.rotation.z=ring;antennaR.rotation.z=-ring;richieHead.rotation.x=T.MathUtils.clamp(-vy*.03,-.25,.25)*(state==='play'?1:0);sun.position.copy(p).add(new T.Vector3(-10,20,-10));if(state==='title'){const t=now*.001;richie.position.set(2,2+Math.abs(Math.sin(t))*1.2,4);richie.scale.setScalar(2);richie.rotation.y=Math.PI+t*.2;camera.position.set(5,4,-7);camera.lookAt(0,2,4)}else richie.scale.setScalar(1);
 if(state==='cinematic'){cine+=d;const shots=[['KINEPOLIS · ANTWERP',new T.Vector3(8,9,-20),new T.Vector3(0,4,-5)],['DEVOXX BELGIUM',new T.Vector3(-7,5,25),new T.Vector3(0,2,52)],['THE KEYNOTE IS UPSTAIRS.',new T.Vector3(7,10,109),new T.Vector3(0,7,126)],['KEYNOTE STARTS IN 10:00',new T.Vector3(0,16,198),new T.Vector3(0,8,262)],['ONE SMALL PROBLEM.',new T.Vector3(2,2,0),new T.Vector3(0,.8,4)],['RICHIE HAS NO LEGS.',new T.Vector3(1,1,1),new T.Vector3(0,.2,4)],['PLEASE DO NOT THROW RICHIE',new T.Vector3(2,1,0),new T.Vector3(0,1,4)]] as const;const i=Math.min(6,Math.floor(cine/2.6));el('cinemaText').textContent=shots[i][0];camera.position.lerp(shots[i][1],.08);camera.lookAt(shots[i][2]);if(cine>18||skipReq||press.has('Space')||press.has('Enter')||press.has('KeyE')){skipReq=false;play()}}
 else if(state==='play'){if(freeLook){camera.position.copy(freeLook.pos);camera.lookAt(freeLook.at)}else{camera.position.lerp(camTarget(p),.12);camera.lookAt(p.x,p.y+.7,p.z)}}
 else if(state==='end'){endT+=d;camera.position.lerp(new T.Vector3(0,12,231),.05);camera.lookAt(0,7.5,256);if(endT>4)showResults()}
 if(state==='play'){el('zone').textContent=String(cp+1).padStart(2,'0')+' / '+zones[cp][0];el('time').textContent=st.time>600?'FASHIONABLY LATE':fmt(600-st.time);el('tokens').textContent=coins+' / 8 TOKENS';el('bar').style.width=(Math.max(charge,helperCharge)*100)+'%';const pp=player.translation();const HK=touch?'HOP':'SPACE';el('hint').textContent=mode==='voxxy'?`VOXXY · HOLD ${HK} TO THROW`:mode==='biggy'?`BIGGY · HOLD ${HK} FOR MAXIMUM CHAOS`:pp.z>57&&pp.z<68?'E · VOXXY CAN HELP':pp.z>118&&pp.z<136?'E · ASK BIGGY':Math.abs(pp.z-207)<5?'E · DROID: RECLINE':`${HK} TO HOP`;toastT-=d;if(toastT<=0)el('toast').textContent=''}press.clear();release.clear();renderer.render(scene,camera);document.getElementById('boot')?.remove()}
function camTarget(p:T.Vector3){const off=new T.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)).multiplyScalar(dist+Math.min(8,player.linvel().y>8?5:0));return p.clone().add(new T.Vector3(0,.7,0)).add(off)}
function fmt(s:number){return Math.floor(Math.max(0,s)/60).toString().padStart(2,'0')+':'+Math.floor(Math.max(0,s)%60).toString().padStart(2,'0')}
// Debug hook. The release screenshots drive the game through this rather than by
// synthesising input against a physics simulation, so the captures are deterministic.
// See scripts/screenshots.mjs.
(globalThis as any).__richie={get state(){return state},get keys(){return [...keys]},get zone(){return cp},get mode(){return mode},get stats(){return st},
 start(skipIntro=true){start();if(skipIntro&&state==='cinematic')play()},
 cinematic(shot=0){start();state='cinematic';el('cinema').hidden=false;cine=shot*2.6},
 warp(i:number){cp=Math.round(T.MathUtils.clamp(i,0,zones.length-1));reset();play();return zones[cp][0]},
 hop(c=1){player.setLinvel({x:0,y:4.5+c*5.5,z:2.5+c*5},true);player.setAngvel({x:1.5,y:.2,z:0},true);st.hops++;charge=0},
 charging(c=1){charge=T.MathUtils.clamp(c,0,1)},
 look(px:number,py:number,pz:number,ax:number,ay:number,az:number){freeLook={pos:new T.Vector3(px,py,pz),at:new T.Vector3(ax,ay,az)}},
 camera(y=0,p=.42,d=8){freeLook=null;yaw=y;pitch=p;dist=d;const t=new T.Vector3().copy(player.translation());camera.position.copy(camTarget(t));camera.lookAt(t.x,t.y+.7,t.z)},
 set(o:{tokens?:number,stats?:Partial<Stats>}){if(o.tokens!==undefined){const n=o.tokens;coins=n;tokens.forEach((x,i)=>x.visible=i>=n)}if(o.stats)Object.assign(st,o.stats)},
 results(){showResults()},
 pose(){const t=player.translation();return{x:t.x,y:t.y,z:t.z,zone:cp,state}}};
requestAnimationFrame(loop);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
