import './style.css';import * as T from 'three';import R from '@dimforge/rapier3d-compat';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import richieUrl from './assets/richie.glb?url';import {G,DT,zones,stats,ballistic,type Stats} from './core';
declare const __APP_VERSION__:string;
await R.init();
const app=document.querySelector('#app')!,canvas=document.createElement('canvas');app.append(canvas);
app.insertAdjacentHTML('beforeend',`<section id="title" class="screen"><div><span class="tag">DEVOXX BELGIUM · ROBOT GAMES</span><h1>PLEASE<br>DO NOT<br><em>THROW</em><br>RICHIE.</h1><p class="sub">AN IRRESPONSIBLE DEVOXX PHYSICS GAME</p><p class="copy">Richie has a keynote. Richie has no legs.<br>Gravity is about to become a team sport.</p><p id="touchNote" class="touch" hidden>Richie is steered with a <b>keyboard</b>. On a phone or tablet you can watch the opening, but the hopping needs a desktop browser.</p><button id="start" class="btn">LET’S MAKE THIS WORSE ↗</button><button id="playground" class="btn alt">PHYSICS PLAYGROUND</button></div></section>
<div id="hud" class="hud" hidden><div class="top"><div><div class="brand">PLEASE DO NOT THROW RICHIE.</div><div id="zone" class="zone"></div></div><div class="timer"><small>KEYNOTE STARTS IN</small><span id="time">10:00</span><div id="tokens" class="zone">0 / 8 TOKENS</div></div></div><div id="toast" class="toast"></div><div id="hint" class="hint">SPACE TO HOP</div><div class="controls"><kbd>WASD</kbd> aim · <kbd>SPACE</kbd> charge/hop · <kbd>E</kbd> assist · <kbd>R</kbd> reset · drag camera</div><div class="charge"><span>QUESTIONABLE POTENTIAL</span><div><i id="bar"></i></div></div></div>
<div id="cinema" class="cinema" hidden><span id="cinemaText"></span></div>
<div id="results" class="modal" hidden><div class="panel"><span class="tag">AGAINST ALL REASONABLE EXPECTATIONS</span><h2>KEYNOTE READY.</h2><div id="stats" class="stats"></div><button id="again" class="btn">ONE MORE BAD IDEA ↗</button></div></div>
<div class="version">v${__APP_VERSION__}</div>`);
const el=(id:string)=>document.getElementById(id)!;const renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new T.Scene();scene.background=new T.Color(0x142b3b);scene.fog=new T.Fog(0x142b3b,45,110);const camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.1,350);
scene.add(new T.HemisphereLight(0xd8ecf2,0x3d4654,2.5));const sun=new T.DirectionalLight(0xffe1bd,3);sun.position.set(-10,20,-10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const world=new R.World({x:0,y:-G,z:0});world.timestep=DT;const mat=(c:T.ColorRepresentation,m=0)=>new T.MeshStandardMaterial({color:c,roughness:.65,metalness:m});
const solids:T.Mesh[]=[];function box(x:number,y:number,z:number,w:number,h:number,d:number,c:T.ColorRepresentation,physical=true){const q=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));q.position.set(x,y,z);q.castShadow=q.receiveShadow=true;scene.add(q);solids.push(q);if(physical)world.createCollider(R.ColliderDesc.cuboid(w/2,h/2,d/2).setTranslation(x,y,z).setFriction(.85));return q}
function cyl(x:number,y:number,z:number,r:number,h:number,c:T.ColorRepresentation,parent: T.Object3D=scene){const q=new T.Mesh(new T.CylinderGeometry(r,r,h,16),mat(c));q.position.set(x,y,z);q.castShadow=true;parent.add(q);return q}
function sph(x:number,y:number,z:number,r:number,c:T.ColorRepresentation,parent:T.Object3D=scene,sx=1,sy=1,sz=1){const q=new T.Mesh(new T.SphereGeometry(r,20,14),mat(c));q.position.set(x,y,z);q.scale.set(sx,sy,sz);q.castShadow=true;parent.add(q);return q}
function label(text:string,x:number,y:number,z:number,w=7,bg='#17303d',faceBack=false){const c=document.createElement('canvas');c.width=1024;c.height=220;const g=c.getContext('2d')!;g.fillStyle=bg;g.fillRect(0,0,1024,220);g.fillStyle='#f8e9c9';g.font='bold 65px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(text,512,110,960);const q=new T.Mesh(new T.PlaneGeometry(w,w*.215),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),side:T.DoubleSide}));q.position.set(x,y,z);q.rotation.y=faceBack?0:Math.PI;scene.add(q);return q}
function floor(a:number,b:number,y:number,w=22,c=0x70838a){box(0,y-.5,(a+b)/2,w,1,b-a,c);for(const x of [-w/2,w/2])box(x,y+1,(a+b)/2,.25,2,b-a,0x284451)}
// The three Devoxx robots, built to their reference-sheet descriptions (docs/ASSET-SOURCES.md).
function part(geo:T.BufferGeometry,c:T.ColorRepresentation,parent:T.Object3D,x:number,y:number,z:number,rx=0,ry=0,rz=0,rough=.65,metal=0){const q=new T.Mesh(geo,new T.MeshStandardMaterial({color:c,roughness:rough,metalness:metal}));q.position.set(x,y,z);q.rotation.set(rx,ry,rz);q.castShadow=q.receiveShadow=true;parent.add(q);return q}
function robot(kind:'voxxy'|'droid'|'biggy'){const g=new T.Group();
 if(kind==='voxxy'){// Orange, rounded, compact: light, curious and quick on its feet.
  const O=0xf07a2a,D=0xc45e1c,K=0x1a2830;part(new T.SphereGeometry(.62,28,20),O,g,0,1.05,0,0,0,0,.5).scale.set(1,1.12,.92);part(new T.SphereGeometry(.5,20,14),D,g,0,.85,.28).scale.set(.8,.7,.55);
  part(new T.SphereGeometry(.5,24,16),K,g,0,1.18,.36,0,0,0,.3).scale.set(.88,.5,.32);for(const x of [-.19,.19]){part(new T.SphereGeometry(.09,12,10),0xa8fbff,g,x,1.2,.68,0,0,0,.2);part(new T.SphereGeometry(.035,8,8),0xffffff,g,x+.03,1.23,.75)}
  part(new T.CylinderGeometry(.025,.025,.3,8),K,g,0,1.85,-.05);part(new T.SphereGeometry(.07,10,8),O,g,0,2.02,-.05);
  for(const s of [-1,1]){part(new T.CylinderGeometry(.11,.09,.5,12),0x6a7a84,g,s*.62,1.0,0,0,0,s*.35,.5,.4);part(new T.SphereGeometry(.13,12,10),O,g,s*.78,.75,.02);
   part(new T.SphereGeometry(.16,12,10),0x53636c,g,s*.28,.48,0,0,0,0,.5,.4);part(new T.CylinderGeometry(.075,.075,.42,10),0x6a7a84,g,s*.3,.3,0,0,0,0,.5,.4);part(new T.SphereGeometry(.09,10,8),0x53636c,g,s*.3,.12,0,0,0,0,.5,.4);
   part(new T.SphereGeometry(.24,14,10),O,g,s*.3,.08,.08,0,0,0,.5).scale.set(1,.42,1.35)}}
 if(kind==='droid'){// Tall, weathered and deliberate: exposed joints, scuffed panels, been here a long time.
  const G=0x4e5a63,S=0x6b5a47,J=0x8c9aa2,P=0x3a4550;const joint=(x:number,y:number,z:number,r=.11)=>part(new T.SphereGeometry(r,12,10),J,g,x,y,z,0,0,0,.35,.6);
  for(const s of [-1,1]){part(new T.CylinderGeometry(.06,.07,1.1,10),G,g,s*.25,.56,0,0,0,0,.6,.5);joint(s*.25,1.14,0);part(new T.CylinderGeometry(.07,.06,1.05,10),G,g,s*.25,1.66,0,0,0,0,.6,.5);part(new T.CylinderGeometry(.025,.025,.9,6),J,g,s*.32,1.62,.09,0,0,0,.3,.7);joint(s*.25,2.2,0,.13);
   part(new T.BoxGeometry(.34,.08,.5),P,g,s*.25,.04,.06,0,0,0,.8);part(new T.BoxGeometry(.14,.06,.18),S,g,s*.25,.09,.2,0,0,0,.9)}
  const torso=part(new T.BoxGeometry(.9,1.15,.55),G,g,0,2.85,0,0,0,0,.7,.4);part(new T.BoxGeometry(.5,.55,.06),S,g,.12,2.7,.29,0,0,.05,.9);part(new T.BoxGeometry(.35,.3,.06),P,g,-.22,3.05,.29,0,0,0,.9);part(new T.BoxGeometry(.92,.12,.57),P,g,0,2.3,0,0,0,0,.8);
  for(let i=0;i<3;i++)part(new T.CylinderGeometry(.03,.03,.5,6),S,g,-.46,2.6+i*.18,.1,0,0,Math.PI/2,.9);part(new T.CylinderGeometry(.14,.14,.3,10),J,g,0,3.55,0,0,0,0,.3,.7);
  for(const s of [-1,1]){joint(s*.55,3.3,0,.14);part(new T.CylinderGeometry(.06,.055,.85,10),G,g,s*.62,2.85,.05,.1,0,s*.12,.6,.5);joint(s*.69,2.42,.1,.1);part(new T.CylinderGeometry(.05,.045,.8,10),G,g,s*.72,2.0,.18,.25,0,0,.6,.5);part(new T.BoxGeometry(.14,.22,.12),P,g,s*.74,1.55,.28,0,0,0,.8)}
  part(new T.BoxGeometry(.62,.42,.5),G,g,0,3.9,.04,0,0,0,.7,.4);part(new T.BoxGeometry(.5,.12,.06),0x2b1f14,g,0,3.92,.3,0,0,0,.4);part(new T.BoxGeometry(.44,.05,.02),0xe9b45c,g,0,3.92,.33,0,0,0,.3);part(new T.BoxGeometry(.2,.18,.2),S,g,.16,4.2,-.08,0,0,0,.9);part(new T.CylinderGeometry(.02,.02,.5,6),J,g,-.2,4.35,-.1,0,0,0,.3,.7);
  g.rotation.z=.02;torso.rotation.x=.04;g.scale.setScalar(.8)}
 if(kind==='biggy'){// Short legs, heavy armour, no hurry: slow to start and hard to stop.
  const B=0x4f6f86,A=0x3c5568,Or=0xd8742f,K=0x1c2a33;const hull=part(new T.BoxGeometry(2.4,1.25,1.7),B,g,0,1.05,0,0,0,0,.6,.35);hull.geometry.translate(0,0,0);
  part(new T.BoxGeometry(2.55,.5,1.85),A,g,0,.62,0,0,0,0,.7,.4);part(new T.BoxGeometry(2.3,.32,.4),Or,g,0,.78,.98,0,0,0,.5);part(new T.BoxGeometry(2.3,.32,.4),Or,g,0,.78,-.98,0,0,0,.5);
  for(const s of [-1,1]){part(new T.BoxGeometry(.18,1.0,1.55),A,g,s*1.28,1.15,0,0,0,0,.7,.4);for(let i=0;i<4;i++)part(new T.SphereGeometry(.05,8,6),K,g,s*1.38,.8+i*.24,-.6,0,0,0,.4,.7);for(let i=0;i<4;i++)part(new T.SphereGeometry(.05,8,6),K,g,s*1.38,.8+i*.24,.6,0,0,0,.4,.7)}
  part(new T.BoxGeometry(1.6,.7,.25),A,g,0,1.3,.9,-.35,0,0,.7,.4);part(new T.BoxGeometry(2.0,.3,1.2),A,g,0,1.75,-.1,0,0,0,.7,.4);
  for(const [x,z] of [[-.85,-.55],[.85,-.55],[-.85,.55],[.85,.55]]){part(new T.CylinderGeometry(.2,.22,.32,12),K,g,x,.2,z,0,0,0,.6,.5);part(new T.BoxGeometry(.6,.14,.5),A,g,x,.07,z,0,0,0,.8)}
  part(new T.BoxGeometry(1.05,.55,.8),B,g,0,1.98,.35,0,0,0,.6,.35);part(new T.BoxGeometry(.9,.14,.08),K,g,0,2.02,.77,0,0,0,.3);part(new T.BoxGeometry(.8,.06,.03),Or,g,0,2.02,.8,0,0,0,.3);part(new T.BoxGeometry(.3,.1,.3),Or,g,-.7,2.3,-.3,0,0,0,.5);part(new T.CylinderGeometry(.06,.06,.5,8),K,g,.8,2.05,-.4,0,0,0,.5,.5)}
 return g}
const player=world.createRigidBody(R.RigidBodyDesc.dynamic().setTranslation(0,.8,4).setLinearDamping(.18).setAngularDamping(1.2).setCcdEnabled(true));const pc=world.createCollider(R.ColliderDesc.cuboid(.3,.44,.3).setMass(1.2).setFriction(.9).setRestitution(.23),player);
// Richie is the official Reachy Mini geometry (scripts/build-richie.py), 3.5x life size so a
// 28 cm robot reads at game scale. The GLB's base sits at y=0; the rigid body's origin is
// the collider centre, so the model hangs 0.44 below it. Antennas and head are separate
// nodes pivoted on the real joints.
const richie=new T.Group();scene.add(richie);const richieModel=(await new GLTFLoader().loadAsync(richieUrl)).scene;richieModel.scale.setScalar(3.5);richieModel.position.y=-.44;richieModel.traverse(o=>{if((o as T.Mesh).isMesh){o.castShadow=true;const m=(o as T.Mesh).material as T.MeshStandardMaterial;if(m.transparent)m.depthWrite=false}});richie.add(richieModel);
const antennaL=richieModel.getObjectByName('antenna_left')!,antennaR=richieModel.getObjectByName('antenna_right')!,richieHead=richieModel.getObjectByName('head')!;
// Continuous venue: registration, exhibition, gap, stairs, upper foyer, corridor, auditorium, stage.
floor(-12,66,0);floor(81,90,0);floor(114,136,6);floor(147,224,13,24,0x495661);floor(246,266,14,24,0x273b49);
label('KINEPOLIS · DEVOXX',0,7,-7,14,'#17303d',true);
// Ground floor: the entrance stairs at the bottom of the plan, reception, the BOF rooms and the exhibition hall.
for(let i=0;i<3;i++)box(0,-(i+1)*.35+.17,-5-i*1.2,14,.35,1.2,0x5e6f77);label('ENTRANCE',0,2.4,-9,5,'#17303d',true);
box(-7,1.2,14,6,2.4,2,0xe5ddca);label('RECEPTION · REGISTRATION',-7,1.5,12.9,5.6,'#e5ddca');
for(const [s,n] of [[-1,'BOF 1'],[1,'BOF 2'],[-1,'BOF 3'],[1,'BOF 4']] as const){const z=n.endsWith('1')||n.endsWith('2')?18:26;box(s*10.7,1.3,z,.4,2.6,2.2,0x1d2f3a,false);label(n,s*10.45,2.9,z,2.2,'#22323b')}label('EXHIBITION HALL',0,5.5,30,10);
for(let z=8;z<27;z+=5)for(const x of [-3,3]){cyl(x,.7,z,.08,1.4,0xaab8ba);box(x,.8,z+2,.08,.12,4,0x24343e)}
for(let z=34;z<59;z+=9)for(const s of [-1,1]){box(s*8,1,z,4,2,3,s>0?0x315b6b:0x744955);label(z%2?'ROBOT LAB':'DEVOXX',s*8,3.2,z-1.55,3.8)}
label('KEYNOTE ↑',0,5.3,59,7);const voxxy=robot('voxxy');voxxy.position.set(-2,0,63);voxxy.rotation.y=Math.PI;scene.add(voxxy);
for(let i=0;i<24;i++){const h=(i+1)*.25;box(0,h/2,90+i+.5,14,h,1,0x718089)}
// Escalators flank the grand staircase up to the cinema level: a ramp collider each, with handrails.
for(const s of [-1,1]){const q=new T.Mesh(new T.BoxGeometry(2.6,.3,24.8),mat(0x3f4d56));q.position.set(s*8.4,3.1,102);q.rotation.x=-Math.atan2(6,24);q.receiveShadow=true;scene.add(q);world.createCollider(R.ColliderDesc.cuboid(1.3,.15,12.4).setTranslation(s*8.4,3.1,102).setRotation({x:Math.sin(-Math.atan2(6,24)/2),y:0,z:0,w:Math.cos(-Math.atan2(6,24)/2)}).setFriction(.3));for(const r of [-1.2,1.2]){const h=new T.Mesh(new T.BoxGeometry(.08,1,24.8),mat(0x9fb0b8,.6));h.position.set(s*8.4+r,4.0,102);h.rotation.x=-Math.atan2(6,24);scene.add(h)}label('ESCALATOR',s*8.4,7.6,114.6,2.6)}label('GRAND STAIRCASE',0,7.2,89.4,7);
label('FOYER · CINEMA LEVEL',0,10,117,10);const biggy=robot('biggy');biggy.position.set(0,6,121);biggy.rotation.y=Math.PI;scene.add(biggy);label('HEAVY ASSISTANCE',-5,9,127,6);box(8,6.6,130,4,1.2,1.4,0x8a6a4a);label('FOYER BAR',8,8.2,129.2,3.4,'#4a3a2a');
box(0,9.3,146,24,7.4,1,0x304a58);
// The corridor between the auditoriums: rooms 1-14 on the plan, 8 is where the keynote is.
for(let i=0;i<14;i++){const n=i+1;if(n===8)continue;const s=n<8?-1:1,z=150+(n<8?n-1:n-8)*5.2;box(s*11.7,14.3,z,.4,2.6,2.4,0x1a2830,false);label('AUDITORIUM '+n,s*11.45,16.1,z,2.6,'#1f2f38')}
for(let i=0;i<6;i++){const z=154+i*5;const g=robot(i%2?'droid':'voxxy');g.scale.setScalar(.55);g.position.set((i%2?1:-1)*8.5,13,z);g.rotation.y=(i%2?1:-1)*Math.PI/2;scene.add(g)}
label('AUDITORIUM 8 · KEYNOTE',0,17,184,11);for(let row=0;row<7;row++)for(let col=0;col<10;col++){const x=(col-4.5)*1.8;if(Math.abs(x)<1.5){continue}box(x,13.5,190+row*3.6,1.2,1,1.3,0x873f38)}
const droid=robot('droid');droid.position.set(-3,13,207);droid.rotation.y=Math.PI*.75;scene.add(droid);const chair=box(0,13.5,207,1.7,.8,1.4,0xb4493d);
for(let i=0;i<3;i++){const z=227+i*8;for(let j=0;j<9;j++){const x=(j%3-1)*.8+(i%2?1.5:-1.5),zz=z+Math.floor(j/3)*.65;sph(x,14.5,zz,.22,0xc9a382);box(x,13.8,zz,.5,.8,.35,[0x558a97,0xb27d55,0x735d82][j%3])}}
box(0,19,260,24,10,.5,0x0f202b);label('DEVOXX · KEYNOTE READY',0,19,259.6,15);const spots=[-8,8].map(x=>{const s=new T.SpotLight(0xffd29b,0,40,Math.PI/5,.7);s.position.set(x,23,252);s.target.position.set(0,14,255);scene.add(s,s.target);return s});
const tokenPos=[[5,1,21],[-5,1,43],[4,1,84],[-7,4,103],[5,7,125],[-7,14,170],[7,14,200],[0,17,236]],tokens:T.Mesh[]=[];for(const [x,y,z] of tokenPos){const q=new T.Mesh(new T.OctahedronGeometry(.35),mat(0xffc64e,.6));q.position.set(x,y,z);scene.add(q);tokens.push(q)}
const keys=new Set<string>(),press=new Set<string>(),release=new Set<string>();addEventListener('keydown',e=>{if(!keys.has(e.code))press.add(e.code);keys.add(e.code);if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>{keys.delete(e.code);release.add(e.code)});let drag=false,yaw=0,pitch=.42,dist=8;canvas.onpointerdown=()=>drag=true;canvas.onpointerup=()=>drag=false;canvas.onpointermove=e=>{if(drag){yaw-=e.movementX*.004;pitch=T.MathUtils.clamp(pitch+e.movementY*.003,.15,1.1)}};canvas.onwheel=e=>dist=T.MathUtils.clamp(dist+e.deltaY*.008,4,16);
let audio:AudioContext|null=null;function tone(a:number,b:number,d=.16,type:OscillatorType='sine'){audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type=type;o.frequency.setValueAtTime(a,t);o.frequency.exponentialRampToValueAtTime(b,t+d);g.gain.setValueAtTime(.12,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(audio.destination);o.start();o.stop(t+d)}
let wobble=0,lastVy=0,freeLook:{pos:T.Vector3,at:T.Vector3}|null=null;
let state:'title'|'cinematic'|'play'|'end'|'results'='title',playground=false,st:Stats=stats(),cp=0,charge=0,ground=false,mode:'richie'|'voxxy'|'biggy'='richie',helperCharge=0,reclines=0,crowd=0,coins=0,toastT=0,cine=0,endT=0,prevVy=0,tumble=0,biggyZ=121;
const say=(s:string,t=1.4)=>{el('toast').textContent=s;toastT=t};function reset(){const q=zones[cp];player.setTranslation({x:q[1],y:q[2]+.8,z:q[3]},true);player.setLinvel({x:0,y:0,z:0},true);player.setAngvel({x:0,y:0,z:0},true);player.setRotation({x:0,y:0,z:0,w:1},true);mode='richie';helperCharge=0;charge=0}
function play(){state='play';freeLook=null;el('title').hidden=true;el('cinema').hidden=true;el('results').hidden=true;el('hud').hidden=false}
function start(){st=stats();cp=0;coins=0;tokens.forEach(x=>x.visible=true);reset();el('title').hidden=true;el('hud').hidden=true;if(playground){play()}else{state='cinematic';el('cinema').hidden=false;cine=0}}
function showResults(){state='results';el('hud').hidden=true;el('results').hidden=false;el('stats').innerHTML=[['TIME',fmt(st.time)],['HOPS',st.hops],['FACEPLANTS',st.faceplants],['VOXXY THROWS',st.throws],['BIGGY IMPACTS',st.impacts],['UNINTENDED STAIR DESCENTS',st.stairs],['COFFEES DESTROYED',st.coffees],['CROISSANTS DESTROYED',st.croissants],['TOKENS',coins+'/8'],['DEVELOPERS INJURED','0*']].map(x=>'<span>'+x[0]+'</span><b>'+x[1]+'</b>').join('')}
if(matchMedia('(pointer:coarse)').matches)el('touchNote').hidden=false;
el('start').onclick=start;el('again').onclick=()=>{el('results').hidden=true;start()};el('playground').onclick=()=>{playground=true;start()};
function step(dt:number){const p=player.translation(),v=player.linvel();const hit=world.castRay(new R.Ray(p,{x:0,y:-1,z:0}),.7,true,undefined,undefined,pc,player);const was=ground;ground=!!hit&&v.y<1.5;const q=new T.Quaternion().copy(player.rotation()),up=new T.Vector3(0,1,0).applyQuaternion(q);if(ground&&!was&&Math.abs(prevVy)>4){if(up.y<.65)st.faceplants++;say(Math.abs(prevVy)>12?'RICHIE DISAGREES':'BONK',.7)}if(ground&&up.y<.96){tumble+=dt;if(tumble>1){player.setRotation(q.slerp(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),yaw),dt*8),true);player.setAngvel({x:0,y:0,z:0},true)}}else tumble=0;
 const f=new T.Vector3(-Math.sin(yaw),0,Math.cos(yaw)),r=new T.Vector3(-Math.cos(yaw),0,-Math.sin(yaw));const dir=f.multiplyScalar((keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)).add(r.multiplyScalar((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0))).clampLength(0,1);
 if(press.has('KeyR')){reset();say('RETRY-DRIVEN DEVELOPMENT')}if(mode==='richie'){if(keys.has('Space')&&ground)charge=Math.min(1,charge+dt);if(release.has('Space')&&ground){const c=Math.max(.08,charge);player.setLinvel({x:dir.x*(2.5+c*5),y:4.5+c*5.5,z:dir.z*(2.5+c*5)},true);player.setAngvel({x:dir.z*1.5,y:.2,z:-dir.x*1.5},true);st.hops++;tone(180,580);charge=0}if(!ground&&dir.lengthSq())player.applyImpulse({x:dir.x*dt,z:dir.z*dt,y:0},true)}
 if(press.has('KeyE')){if(mode!=='richie'){mode='richie'}else if(p.z>57&&p.z<68){mode='voxxy';player.setGravityScale(0,true);say('VOXXY CAN HELP')}else if(p.z>118&&p.z<136){mode='biggy';biggyZ=121;helperCharge=0;player.setTranslation({x:0,y:7,z:132},true);say('HIT RICHIE VERY HARD')}else if(Math.abs(p.z-207)<5){reclines++;say(reclines%3?'RECLINE. …NOTHING.':'EJECT MODE');if(reclines%3===0)player.setLinvel(ballistic(p,{x:0,y:14,z:221},1.45),true)}}
 if(mode==='voxxy'){player.setTranslation({x:-2,y:2,z:63},true);player.setLinvel({x:0,y:0,z:0},true);if(keys.has('Space'))helperCharge=Math.min(1,helperCharge+dt);if(release.has('Space')){player.setGravityScale(1,true);player.setLinvel(ballistic(player.translation(),{x:dir.x*4,y:1,z:85+helperCharge*2},1.55),true);mode='richie';st.throws++;tone(140,700,.45,'sawtooth');say('THE TITLE WAS A SUGGESTION');helperCharge=0}}
 if(mode==='biggy'){if(keys.has('Space'))helperCharge=Math.min(1,helperCharge+dt);if(release.has('Space')){player.setLinvel(ballistic(p,{x:dir.x*5,y:14,z:152+helperCharge*4},1.8),true);st.impacts++;mode='richie';tone(85,22,.6,'sawtooth');say(helperCharge>.8?'ORBIT ACHIEVED':'THIS SEEMS UNSAFE');helperCharge=0}}
 world.step();prevVy=v.y;const np=player.translation();for(let i=cp+1;i<zones.length;i++){const z=zones[i];if(np.z>=z[3]&&np.y>=z[2]-.5){cp=i;say('CHECKPOINT · '+z[0])}}tokens.forEach((x,i)=>{x.rotation.y+=dt*2;if(x.visible&&x.position.distanceTo(new T.Vector3().copy(np))<1.2){x.visible=false;coins++;say('EXTREMELY NECESSARY TOKEN')}});if(np.z>221&&np.y<17&&np.y>10&&crowd<3){const target=crowd===2?{x:0,y:15,z:254}:{x:(crowd%2?1:-1)*1.5,y:15,z:235+crowd*8};player.setLinvel(ballistic(np,target,crowd===2?2:1.3),true);crowd++;say(crowd===3?'ONE LAST BAD IDEA':'AUDIENCE PARTICIPATION')}if(np.z>250&&np.y<16&&crowd===3){state='end';endT=0;say('WHAM');spots.forEach(s=>s.intensity=80)}if(np.y<(cp>4?5:-8)||Math.abs(np.x)>25)reset();st.time+=dt}
let last=performance.now(),acc=0,frames=0;function loop(now:number){requestAnimationFrame(loop);const d=Math.min(.2,(now-last)/1000);last=now;if(state==='play'||state==='end'){acc+=d;let n=0;while(acc>=DT&&n++<12){step(DT);acc-=DT}}const p=new T.Vector3().copy(player.translation());richie.position.copy(p);richie.quaternion.copy(player.rotation());
 // Antennas are springs: a landing or launch sets them ringing, and the finale is a celebration.
 const vy=player.linvel().y;wobble=Math.min(1.2,wobble*Math.pow(.15,d)+Math.abs(vy-lastVy)*.08);lastVy=vy;const t=now*.001,ring=(state==='end'||state==='results'?.55*Math.sin(t*9):Math.sin(t*16)*wobble)+(state==='title'?Math.sin(t*2.2)*.1:0);antennaL.rotation.z=ring;antennaR.rotation.z=-ring;richieHead.rotation.x=T.MathUtils.clamp(-vy*.03,-.25,.25)*(state==='play'?1:0);sun.position.copy(p).add(new T.Vector3(-10,20,-10));if(state==='title'){const t=now*.001;richie.position.set(2,2+Math.abs(Math.sin(t))*1.2,4);richie.scale.setScalar(2);richie.rotation.y=Math.PI+t*.2;camera.position.set(5,4,-7);camera.lookAt(0,2,4)}else richie.scale.setScalar(1);
 if(state==='cinematic'){cine+=d;const shots=[['KINEPOLIS · ANTWERP',new T.Vector3(8,9,-20),new T.Vector3(0,4,-5)],['DEVOXX BELGIUM',new T.Vector3(-7,5,25),new T.Vector3(0,2,52)],['THE KEYNOTE IS UPSTAIRS.',new T.Vector3(7,10,109),new T.Vector3(0,7,126)],['KEYNOTE STARTS IN 10:00',new T.Vector3(0,20,204),new T.Vector3(0,17,259)],['ONE SMALL PROBLEM.',new T.Vector3(2,2,0),new T.Vector3(0,.8,4)],['RICHIE HAS NO LEGS.',new T.Vector3(1,1,1),new T.Vector3(0,.2,4)],['PLEASE DO NOT THROW RICHIE',new T.Vector3(2,1,0),new T.Vector3(0,1,4)]] as const;const i=Math.min(6,Math.floor(cine/2.6));el('cinemaText').textContent=shots[i][0];camera.position.lerp(shots[i][1],.08);camera.lookAt(shots[i][2]);if(cine>18)play()}
 else if(state==='play'){if(freeLook){camera.position.copy(freeLook.pos);camera.lookAt(freeLook.at)}else{camera.position.lerp(camTarget(p),.12);camera.lookAt(p.x,p.y+.7,p.z)}}
 else if(state==='end'){endT+=d;camera.position.lerp(new T.Vector3(0,18,239),.05);camera.lookAt(0,16,256);if(endT>4)showResults()}
 if(state==='play'){el('zone').textContent=String(cp+1).padStart(2,'0')+' / '+zones[cp][0];el('time').textContent=st.time>600?'FASHIONABLY LATE':fmt(600-st.time);el('tokens').textContent=coins+' / 8 TOKENS';el('bar').style.width=(Math.max(charge,helperCharge)*100)+'%';const pp=player.translation();el('hint').textContent=mode==='voxxy'?'VOXXY · HOLD SPACE TO THROW':mode==='biggy'?'BIGGY · HOLD SPACE FOR MAXIMUM CHAOS':pp.z>57&&pp.z<68?'E · VOXXY CAN HELP':pp.z>118&&pp.z<136?'E · ASK BIGGY':Math.abs(pp.z-207)<5?'E · DROID: RECLINE':'SPACE TO HOP';toastT-=d;if(toastT<=0)el('toast').textContent=''}press.clear();release.clear();renderer.render(scene,camera);document.getElementById('boot')?.remove()}
function camTarget(p:T.Vector3){const off=new T.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)).multiplyScalar(dist+Math.min(8,player.linvel().y>8?5:0));return p.clone().add(new T.Vector3(0,.7,0)).add(off)}
function fmt(s:number){return Math.floor(Math.max(0,s)/60).toString().padStart(2,'0')+':'+Math.floor(Math.max(0,s)%60).toString().padStart(2,'0')}
// Debug hook. The release screenshots drive the game through this rather than by
// synthesising input against a physics simulation, so the captures are deterministic.
// See scripts/screenshots.mjs.
(globalThis as any).__richie={get state(){return state},get zone(){return cp},get mode(){return mode},get stats(){return st},
 start(skipIntro=true){start();if(skipIntro&&state==='cinematic')play()},
 cinematic(shot=0){start();state='cinematic';el('cinema').hidden=false;cine=shot*2.6},
 warp(i:number){cp=Math.round(T.MathUtils.clamp(i,0,zones.length-1));reset();play();return zones[cp][0]},
 hop(c=1){player.setLinvel({x:0,y:4.5+c*5.5,z:2.5+c*5},true);player.setAngvel({x:1.5,y:.2,z:0},true);st.hops++;charge=0},
 charging(c=1){charge=T.MathUtils.clamp(c,0,1)},
 look(px:number,py:number,pz:number,ax:number,ay:number,az:number){freeLook={pos:new T.Vector3(px,py,pz),at:new T.Vector3(ax,ay,az)}},
 camera(y=0,p=.42,d=8){freeLook=null;yaw=y;pitch=p;dist=d;const t=new T.Vector3().copy(player.translation());camera.position.copy(camTarget(t));camera.lookAt(t.x,t.y+.7,t.z)},
 set(o:{tokens?:number,stats?:Partial<Stats>}){if(o.tokens!==undefined){const n=o.tokens;coins=n;tokens.forEach((x,i)=>x.visible=i>=n)}if(o.stats)Object.assign(st,o.stats)},
 results(){showResults()},
 pose(){const t=player.translation();return{x:t.x,y:t.y,z:t.z,zone:cp,state}}};
requestAnimationFrame(loop);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
