import './style.css';import * as T from 'three';import R from '@dimforge/rapier3d-compat';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import richieUrl from './assets/richie.glb?url';import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';import {registerSW} from 'virtual:pwa-register';import {Robot} from './robots';import {Walker,Guard,seatedAudience,cheeringCrowd,rng} from './people';import {G,DT,zones,stats,ballistic,type Stats} from './core';import {mats,boxGeo,dressVenue,seat,seatMeshes,escalatorSkin,escalatorTick,ESCALATOR_SPEED} from './venue';import {setAnisotropy,texUrl} from './textures';import {cards} from './tutorial';import logoUrl from './assets/devoxx-white.svg?url';import musicUrl from './assets/audio/synaptic-drift.mp3?url';
declare const __APP_VERSION__:string;
registerSW({immediate:true});
await R.init();
const app=document.querySelector('#app')!,canvas=document.createElement('canvas');app.append(canvas);
app.insertAdjacentHTML('beforeend',`<section id="title" class="screen"><div><span class="tag"><img class="dvx" src="${logoUrl}" alt="Devoxx"> BELGIUM · ROBOT GAMES</span><h1>PLEASE<br>DO NOT<br><em>THROW</em><br>RICHIE.</h1><p class="sub">AN IRRESPONSIBLE DEVOXX PHYSICS GAME</p><p class="copy">Richie has a keynote. Richie has no legs.<br>Gravity is about to become a team sport.</p><p class="credit">MUSIC · <b>mITy.John</b> — SYNAPTIC DRIFT<button id="mute" class="linkbtn"></button></p><p id="touchNote" class="tnote" hidden>Touch controls are on: the stick aims, hold <b>HOP</b> to charge and let go to jump, <b>E</b> asks a robot for help, <b>R</b> resets. Landscape works best.</p><button id="start" class="btn">LET’S MAKE THIS WORSE ↗</button><button id="howto" class="btn alt">HOW THIS WORKS · 60 SEC</button></div></section>
<div id="hud" class="hud" hidden><div class="top"><div><div class="brand">PLEASE DO NOT THROW RICHIE.</div><div id="zone" class="zone"></div></div><button id="menuBtn" class="menubtn" title="Pause · Esc">❚❚ MENU</button><div class="timer"><small>KEYNOTE STARTS IN</small><span id="time">10:00</span><div id="tokens" class="zone">0 / 8 TOKENS</div></div></div><div id="toast" class="toast"></div><div id="hint" class="hint">SPACE TO HOP</div><div class="controls"><kbd>WASD</kbd> aim · <kbd>SPACE</kbd> charge/hop · <kbd>E</kbd> assist · <kbd>R</kbd> reset · <kbd>ESC</kbd> menu · <kbd>M</kbd> music · drag camera</div><div class="charge"><span>QUESTIONABLE POTENTIAL</span><div><i id="bar"></i></div></div></div>
<section id="tutorial" class="tut" hidden><div id="tutCard" class="tcard"><span id="tutTag" class="tag"></span><h2 id="tutTitle"></h2><p id="tutBody" class="copy"></p><div id="tutKeys" class="tkeys"></div><div id="tutArt" class="tart"></div><div class="tnav"><button id="tutBack" class="btn alt">← BACK</button><button id="tutNext" class="btn">NEXT →</button><button id="tutSkip" class="btn alt">SKIP</button></div><div id="tutDots" class="tdots"></div></div></section>
<div id="cinema" class="cinema" hidden><span id="cinemaText"></span><small>SPACE · ENTER · TAP TO SKIP</small><button id="skip" class="skipbtn">SKIP ▸</button></div>
<div id="pause" class="modal" hidden><div class="panel"><span class="tag">PAUSED</span><h2>RICHIE WILL WAIT.</h2><p class="copy">He has no legs. He is not going anywhere.</p><button id="resume" class="btn">RESUME ↗</button><button id="pauseMute" class="btn alt"></button><button id="quit" class="btn alt">QUIT TO MENU</button></div></div>
<div id="results" class="modal" hidden><div class="panel"><span class="tag">AGAINST ALL REASONABLE EXPECTATIONS</span><h2>KEYNOTE READY.</h2><div id="stats" class="stats"></div><button id="again" class="btn">ONE MORE BAD IDEA ↗</button><button id="toMenu" class="btn alt">BACK TO MENU</button></div></div>
<div id="touch" class="touch-ui" hidden><div id="stick" class="stick"><i id="stickKnob"></i></div><div class="tbtns"><button id="tE">E<br>ASSIST</button><button id="tHop">HOP</button><button id="tR">R<br>RESET</button></div></div>
<div class="version">v${__APP_VERSION__}</div>`);
const el=(id:string)=>document.getElementById(id)!;const renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;setAnisotropy(renderer.capabilities.getMaxAnisotropy());
const scene=new T.Scene();const sky=scene.background=new T.Color(0x0b1118),fog=scene.fog=new T.Fog(0x0b1118,40,125);const camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.1,350);
// An environment map is what makes plastic shells and glass lenses read as materials at all.
const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.5;pmrem.dispose();
const hemi=new T.HemisphereLight(0xe6eef6,0x4a4f58,1.5);scene.add(hemi);const sun=new T.DirectionalLight(0xfff0dc,2.6);sun.position.set(-10,20,-10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=sun.shadow.camera.bottom=-26;sun.shadow.camera.right=sun.shadow.camera.top=26;sun.shadow.camera.near=1;sun.shadow.camera.far=90;sun.shadow.bias=-.0006;sun.shadow.normalBias=.03;scene.add(sun,sun.target);
const world=new R.World({x:0,y:-G,z:0});world.timestep=DT;const mat=(c:T.ColorRepresentation,m=0)=>new T.MeshStandardMaterial({color:c,roughness:.65,metalness:m});
const solids:T.Mesh[]=[];function box(x:number,y:number,z:number,w:number,h:number,d:number,c:T.ColorRepresentation|T.Material,physical=true){const m=(c as T.Material).isMaterial?c as T.Material:null,q=new T.Mesh(m?boxGeo(w,h,d,m):new T.BoxGeometry(w,h,d),m??mat(c as T.ColorRepresentation));q.position.set(x,y,z);q.castShadow=q.receiveShadow=true;scene.add(q);solids.push(q);if(physical)world.createCollider(R.ColliderDesc.cuboid(w/2,h/2,d/2).setTranslation(x,y,z).setFriction(.85));return q}
function cyl(x:number,y:number,z:number,r:number,h:number,c:T.ColorRepresentation|T.Material,parent: T.Object3D=scene){const q=new T.Mesh(new T.CylinderGeometry(r,r,h,16),(c as T.Material).isMaterial?c as T.Material:mat(c as T.ColorRepresentation));q.position.set(x,y,z);q.castShadow=true;parent.add(q);return q}
function sph(x:number,y:number,z:number,r:number,c:T.ColorRepresentation,parent:T.Object3D=scene,sx=1,sy=1,sz=1){const q=new T.Mesh(new T.SphereGeometry(r,20,14),mat(c));q.position.set(x,y,z);q.scale.set(sx,sy,sz);q.castShadow=true;parent.add(q);return q}
function label(text:string,x:number,y:number,z:number,w=7,bg='#11161b',faceBack=false){const c=document.createElement('canvas');c.width=1024;c.height=220;const g=c.getContext('2d')!;g.fillStyle=bg;g.fillRect(0,0,1024,220);g.fillStyle=bg==='#f0640f'?'#ffffff':'#f0640f';g.fillRect(0,208,1024,12);g.fillStyle='#f8efe0';g.font='800 68px "Helvetica Neue",Arial,sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(text,512,110,960);const tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;tx.anisotropy=8;const q=new T.Mesh(new T.PlaneGeometry(w,w*.215),new T.MeshBasicMaterial({map:tx}));q.position.set(x,y,z);q.rotation.y=faceBack?0:Math.PI;const back=new T.Mesh(q.geometry,q.material);back.rotation.y=Math.PI;back.position.z=-.012;q.add(back);scene.add(q);return q}
function floor(a:number,b:number,y:number,w=22,c:T.Material=mats.hall,wall:T.Material=mats.plaster){box(0,y-.5,(a+b)/2,w,1,b-a,c);for(const x of [-w/2,w/2])box(x,y+1,(a+b)/2,.25,2,b-a,wall)}
const player=world.createRigidBody(R.RigidBodyDesc.dynamic().setTranslation(0,.8,4).setLinearDamping(.18).setAngularDamping(1.2).setCcdEnabled(true));const pc=world.createCollider(R.ColliderDesc.cuboid(.3,.44,.3).setMass(1.2).setFriction(.9).setRestitution(.23),player);
// Richie is the official Reachy Mini geometry (scripts/build-richie.py), 3.5x life size so a
// 28 cm robot reads at game scale. The GLB's base sits at y=0; the rigid body's origin is
// the collider centre, so the model hangs 0.44 below it. Antennas and head are separate
// nodes pivoted on the real joints.
const richie=new T.Group();scene.add(richie);const richieModel=(await new GLTFLoader().loadAsync(richieUrl)).scene;richieModel.scale.setScalar(3.5);richieModel.position.y=-.44;richieModel.traverse(o=>{const m=o as T.Mesh;if(!m.isMesh)return;m.castShadow=true;/* decimation leaves a few zero-length normals; lit, they are NaN, and bloom smears a NaN across the frame */const nn=m.geometry.attributes.normal;for(let i=0;i<nn.count;i++)if(!(Math.hypot(nn.getX(i),nn.getY(i),nn.getZ(i))>1e-4))nn.setXYZ(i,0,1,0);const src=m.material as T.MeshStandardMaterial,c=src.color,shell=c.r>.8;m.material=src.transparent?new T.MeshPhysicalMaterial({color:0x9fc4d8,roughness:.12,metalness:.1,transparent:true,opacity:.5,depthWrite:false}):new T.MeshPhysicalMaterial({color:shell?c.clone().multiplyScalar(.84):c,roughness:shell?.32:.45,metalness:shell?0:.4,clearcoat:shell?.7:.15,clearcoatRoughness:.25})});richie.add(richieModel);
const antennaL=richieModel.getObjectByName('antenna_left')!,antennaR=richieModel.getObjectByName('antenna_right')!,richieHead=richieModel.getObjectByName('head')!;
// Continuous venue: registration, exhibition, gap, stairs, upper foyer, corridor, auditorium, stage.
floor(-12,66,0);floor(81,90,0,22,mats.stone);floor(114,136,6,22,mats.cinema,mats.plasterDark);floor(147,186,13,24,mats.cinema,mats.acoustic);floor(241,270,6.4,26,mats.stage,mats.acoustic);
label('KINEPOLIS · ANTWERP',0,8.35,-9.62,12);
// Ground floor: the entrance stairs at the bottom of the plan, reception, the BOF rooms and the exhibition hall.
for(let i=0;i<3;i++)box(0,-(i+1)*.35+.17,-5-i*1.2,14,.35,1.2,mats.stone);

for(const [s,n] of [[-1,'BOF 1'],[1,'BOF 2'],[-1,'BOF 3'],[1,'BOF 4']] as const){const z=n.endsWith('1')||n.endsWith('2')?18:26;box(s*10.7,1.3,z,.4,2.6,2.2,mats.wood,false);label(n,s*10.45,2.9,z,2.2)}label('EXHIBITION HALL',0,5.5,30,10);
for(let z=8;z<27;z+=5)for(const x of [-3,3]){cyl(x,.7,z,.06,1.4,mats.chrome);cyl(x,.03,z,.22,.06,mats.chrome);box(x,.8,z+2,.08,.12,4,0x7a1414)}
label('KEYNOTE ↑',0,5.3,59,7);const voxxy=new Robot('voxxy').place(-2,0,63,Math.PI).patrol([[-2,0,63],[3,0,60.5],[5.5,0,64],[-4.5,0,65]]);scene.add(voxxy.group);
for(let i=0;i<24;i++){const h=(i+1)*.25;box(0,h/2,90+i+.5,14,h,1,mats.stone)}
// Escalators flank the grand staircase up to the cinema level: a ramp collider each, with handrails.
// They run, so riding one is the alternative to hopping twenty-four steps. The ride itself is in step().
const esc=escalatorSkin(24.8),ESC_A=Math.atan2(6,24),ESC_Y=ESCALATOR_SPEED*Math.sin(ESC_A),ESC_Z=ESCALATOR_SPEED*Math.cos(ESC_A);
for(const s of [-1,1]){const q=new T.Mesh(new T.BoxGeometry(2.6,.3,24.8),esc.tread);q.position.set(s*8.4,3.1,102);q.rotation.x=-Math.atan2(6,24);q.receiveShadow=true;scene.add(q);world.createCollider(R.ColliderDesc.cuboid(1.3,.15,12.4).setTranslation(s*8.4,3.1,102).setRotation({x:Math.sin(-Math.atan2(6,24)/2),y:0,z:0,w:Math.cos(-Math.atan2(6,24)/2)}).setFriction(.3));for(const r of [-1.2,1.2]){const h=new T.Mesh(new T.BoxGeometry(.04,1,24.8),mats.glass);h.position.set(s*8.4+r,4.0,102);h.rotation.x=-Math.atan2(6,24);scene.add(h);const hr=new T.Mesh(new T.BoxGeometry(.1,.07,24.9),esc.rail);hr.position.set(s*8.4+r,4.52,102);hr.rotation.x=-Math.atan2(6,24);scene.add(hr)}for(const [cz,cy] of [[89.98,.1],[114.02,6.1]] as const)box(s*8.4,cy+.17,cz,2.6,.08,.55,mats.comb,false);label('ESCALATOR',s*8.4,7.6,114.6,2.6)}label('GRAND STAIRCASE',0,7.2,89.4,7);
label('FOYER · CINEMA LEVEL',0,10,117,10);const biggy=new Robot('biggy').place(0,6,121,Math.PI).patrol([[0,6,121],[-4,6,124],[3,6,127],[4.5,6,120]]);scene.add(biggy.group);label('HEAVY ASSISTANCE',-5,9,127,6);box(8,6.6,130,4,1.2,1.4,mats.wood);label('FOYER BAR',8.6,8.95,131.45,3.4);
box(0,9.3,146,24,7.4,1,mats.acoustic);
// The corridor between the auditoriums: rooms 1-14 on the plan, 8 is where the keynote is.
for(let i=0;i<14;i++){const n=i+1;if(n===8)continue;const s=n<8?-1:1,z=150+(n<8?n-1:n-8)*5.2;box(s*11.7,14.3,z,.4,2.6,2.4,mats.wood,false);label('AUDITORIUM '+n,s*11.45,16.1,z,2.6)}
const minis:Robot[]=[];for(let i=0;i<4;i++){const z=154+i*7,x=(i%2?1:-1)*8.5;const rb=new Robot(i%2?'droid':'voxxy',.55).place(x,13,z,(i%2?1:-1)*Math.PI/2).patrol([[x,13,z],[x,13,z+3],[x*.7,13,z+1.5]]);scene.add(rb.group);minis.push(rb)}
label('AUDITORIUM 8 · KEYNOTE',0,17,184,11);
// Auditorium 8 the Kinepolis way: you come in at the top and the room rakes down to the
// screen — twelve stepped tiers of gently curved seat rows, an aisle either side of the
// centre block, the front three tiers standing room tonight, then the stage.
const ROWS=12,ROW_D=4.6,Z0=186,rowY=(i:number)=>13-i*.6;
const seatGeo:T.BufferGeometry[]=[],shellGeo:T.BufferGeometry[]=[],seatSpots:{x:number,y:number,z:number}[]=[],crowdSpots:{x:number,y:number,z:number}[]=[];
for(let i=0;i<ROWS;i++){const y=rowY(i),z=Z0+i*ROW_D+ROW_D/2;box(0,y/2,z,26,y,ROW_D,mats.tiers);for(const s of [-1,1])box(s*13.2,y+1.5,z,.4,3,ROW_D,mats.acoustic);
 if(i>=9){for(let c=-6;c<=6;c++)crowdSpots.push({x:c*1.3+(i%2?.55:0),y,z:z-1.3+(c%2?1.8:0)});continue}
 for(let c=-9;c<=9;c++){const x=c*1.2;if(Math.abs(c)===4||(i===4&&Math.abs(x)<1.3))continue;const zz=z+x*x*.012;
  seat(x,y,zz,seatGeo,shellGeo);seatSpots.push({x,y:y+.5,z:zz-.02})}
 for(const [bx,hw] of [[0,4.1],[-8.4,2.95],[8.4,2.95]])world.createCollider(R.ColliderDesc.cuboid(hw,.28,.55).setTranslation(bx,y+.28,z+bx*bx*.012).setFriction(.8))}
scene.add(...seatMeshes(seatGeo,shellGeo));
// Everything that is set dressing rather than route: booths, reception, ceilings, walls, light fittings, the stage rig.
dressVenue({scene,collide:(x,y,z,hw,hh,hd)=>{world.createCollider(R.ColliderDesc.cuboid(hw,hh,hd).setTranslation(x,y,z).setFriction(.85))},rowY,ROWS,ROW_D,Z0});
scene.add(seatedAudience(seatSpots));const crowdM=cheeringCrowd(crowdSpots);scene.add(crowdM.group);let crowdEx=0;
const droid=new Robot('droid').place(-4.7,rowY(4),206,Math.PI*.6).patrol([[-4.7,rowY(4),205],[-4.7,rowY(4),208.4]]);scene.add(droid.group);box(0,rowY(4)+.4,207,1.7,.8,1.4,mats.velvet);label('RECLINE',0,rowY(4)+1.4,207.9,1.6,'#5a1a1a');
box(0,6.65,256,20,.5,16,mats.stage);box(3,7.55,258,.9,1.3,.7,mats.wood);box(0,12.4,269,26,11,.5,mats.ceiling);const spots=[-8,8].map(x=>{const s=new T.SpotLight(0xffd29b,0,40,Math.PI/5,.7);s.position.set(x,17,252);s.target.position.set(0,7,256);scene.add(s,s.target);return s});
// Grand finale props: confetti over the stage (one instanced mesh), and the spot the party
// gathers round once Richie has landed.
const confetti=new T.InstancedMesh(new T.PlaneGeometry(.14,.2),new T.MeshBasicMaterial({side:T.DoubleSide}),260);confetti.visible=false;confetti.frustumCulled=false;scene.add(confetti);
const cf=Array.from({length:260},()=>({p:new T.Vector3(),v:0,r:0,s:0,phase:Math.random()*6}));const cfM=new T.Matrix4(),cfQ=new T.Quaternion(),cfE=new T.Euler(),cfS=new T.Vector3(1,1,1);
function dropConfetti(c:typeof cf[0],initial=false){c.p.set(-10+Math.random()*20,initial?8+Math.random()*10:17+Math.random()*3,247+Math.random()*17);c.v=.9+Math.random()*1.2;c.r=Math.random()*6;c.s=(Math.random()-.5)*6}
cf.forEach((c,i)=>{confetti.setColorAt(i,new T.Color([0xffbd5c,0xf0752a,0x63e6ff,0xf7f4ec,0x8a3fa8,0x2f6b4f][i%6]));dropConfetti(c,true)});confetti.instanceColor!.needsUpdate=true;
function updateConfetti(d:number,t:number){cf.forEach((c,i)=>{c.p.y-=c.v*d;c.p.x+=Math.sin(t*2+c.phase)*d*.8;c.r+=c.s*d;if(c.p.y<7)dropConfetti(c);cfM.compose(c.p,cfQ.setFromEuler(cfE.set(c.r,c.phase,c.r*.7)),cfS);confetti.setMatrixAt(i,cfM)});confetti.instanceMatrix.needsUpdate=true}
let finale:T.Vector3|null=null;
const tokenPos=[[5,1,21],[-5,1,43],[4,1,84],[-7,4,103],[5,7,125],[-7,14,170],[7,12.4,200],[0,8.4,236]],tokens:T.Mesh[]=[];for(const [x,y,z] of tokenPos){const q=new T.Mesh(new T.OctahedronGeometry(.35),new T.MeshStandardMaterial({color:0xffc64e,roughness:.25,metalness:1,emissive:0xff9a1a,emissiveIntensity:.6}));q.position.set(x,y,z);scene.add(q);tokens.push(q)}
const keys=new Set<string>(),press=new Set<string>(),release=new Set<string>();addEventListener('keydown',e=>{if(!keys.has(e.code))press.add(e.code);keys.add(e.code);if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>{keys.delete(e.code);release.add(e.code)});let drag=false,yaw=0,pitch=.42,dist=8,lastPX=0,lastPY=0;canvas.onpointerdown=e=>{drag=true;lastPX=e.clientX;lastPY=e.clientY};canvas.onpointerup=canvas.onpointercancel=()=>drag=false;canvas.onpointermove=e=>{if(!drag)return;const mx=e.clientX-lastPX,my=e.clientY-lastPY;lastPX=e.clientX;lastPY=e.clientY;yaw-=mx*.004;pitch=T.MathUtils.clamp(pitch+my*.003,.15,1.1)};
// Touch: a stick feeds the same aim vector WASD does, and the buttons press the same keys.
const stick={x:0,y:0},touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
if(touch){document.body.classList.add('touch');el('touch').hidden=false;el('touchNote').hidden=false;const st=el('stick'),knob=el('stickKnob');let sid=-1;const moveStick=(e:PointerEvent)=>{const r=st.getBoundingClientRect(),R=r.width/2-8,dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),l=Math.hypot(dx,dy),k=l?Math.min(l,R)/l:0;stick.x=dx*k/R;stick.y=dy*k/R;knob.style.transform=`translate(${dx*k}px,${dy*k}px)`};st.onpointerdown=e=>{sid=e.pointerId;moveStick(e);try{st.setPointerCapture(sid)}catch{}};st.onpointermove=e=>{if(e.pointerId===sid)moveStick(e)};st.onpointerup=st.onpointercancel=e=>{if(e.pointerId===sid){sid=-1;stick.x=stick.y=0;knob.style.transform=''}};
 const bind=(id:string,code:string)=>{const b=el(id);b.onpointerdown=e=>{e.preventDefault();b.classList.add('down');if(!keys.has(code))press.add(code);keys.add(code);try{b.setPointerCapture(e.pointerId)}catch{}};const up=()=>{b.classList.remove('down');if(keys.has(code)){keys.delete(code);release.add(code)}};b.onpointerup=b.onpointercancel=up;b.oncontextmenu=e=>e.preventDefault()};bind('tHop','Space');bind('tE','KeyE');bind('tR','KeyR')}canvas.onwheel=e=>dist=T.MathUtils.clamp(dist+e.deltaY*.008,4,16);
// Music: mITy.John — Synaptic Drift (src/assets/audio/NOTICE-synaptic-drift.md). Streamed from an
// audio element rather than decoded into a buffer: three minutes of 44.1 kHz stereo is 65 MB of
// float32, and a phone has better uses for it. No browser starts audio before a gesture, so the
// first press of anything does — the title screen needs one to get into the game anyway.
const music=new Audio(musicUrl);music.loop=true;music.preload='auto';music.volume=0;
const MUSIC_FULL=.42,MUSIC_DUCK=.12;let muted=false;try{muted=localStorage.getItem('richie.mute')==='1'}catch{}
let musicVol=0,musicWanted=false;
function musicStart(){musicWanted=true;if(!muted&&music.paused)music.play().catch(()=>{})}
function setMuted(on:boolean){muted=on;try{localStorage.setItem('richie.mute',on?'1':'0')}catch{}
 if(on)music.pause();else if(musicWanted&&music.paused)music.play().catch(()=>{});
 for(const id of ['mute','pauseMute'])el(id).textContent=on?'♪ MUSIC OFF':'♪ MUSIC ON'}
// The pause card ducks the track rather than stopping it: the building keeps moving behind it.
function musicTick(d:number){musicVol+=((muted||!musicWanted?0:paused?MUSIC_DUCK:MUSIC_FULL)-musicVol)*Math.min(1,d*1.6);music.volume=Math.max(0,Math.min(1,musicVol))}
let audio:AudioContext|null=null;function tone(a:number,b:number,d=.16,type:OscillatorType='sine'){audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type=type;o.frequency.setValueAtTime(a,t);o.frequency.exponentialRampToValueAtTime(b,t+d);g.gain.setValueAtTime(.12,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(audio.destination);o.start();o.stop(t+d)}
let wobble=0,lastVy=0,freeLook:{pos:T.Vector3,at:T.Vector3}|null=null,skipReq=false,biggyBusyT=0;
// Richie's head rides a spring on the real neck: charging a hop pulls it down into the body,
// the hop lets it go and it overshoots to its top stop before settling. Units are the GLB's
// metres (the model is scaled 3.5x), so 45 mm of travel each way keeps the shell attached.
const headBase=richieHead.position.y,HEAD_DIP=.045,HEAD_POP=.05;let headY=0,headV=0,headKick=false;const robots=[voxxy,biggy,droid,...minis];
// The crowd: people wandering the exhibition hall, the foyer and the corridor, each on a
// private loop of waypoints so no two walk the same beat.
const area=(seed:number,n:number,x0:number,x1:number,z0:number,z1:number,y:number,ok:(x:number,z:number)=>boolean=()=>true)=>{const r=rng(seed),pts:T.Vector3[]=[];while(pts.length<n){const x=x0+r()*(x1-x0),z=z0+r()*(z1-z0);if(ok(x,z))pts.push(new T.Vector3(x,y,z))}return pts};
const hallOk=(x:number,z:number)=>!(Math.abs(Math.abs(x)-8)<3&&[34,43,52].some(bz=>Math.abs(z-bz)<2.6))&&!(Math.abs(x+7)<3.6&&Math.abs(z-14)<1.8)&&!(Math.abs(x)<3.4&&z>7&&z<27&&Math.abs(Math.abs(x)-3)<.5);
const walkers:Walker[]=[];for(let i=0;i<26;i++)walkers.push(new Walker(100+i,area(100+i,5,-9.5,9.5,6,58,0,hallOk)));for(let i=0;i<8;i++)walkers.push(new Walker(200+i,area(200+i,4,-9,9,116,134,6,(x,z)=>!(x>5.5&&Math.abs(z-130)<1.5))));for(let i=0;i<10;i++)walkers.push(new Walker(300+i,area(300+i,4,-9,9,150,183,13)));walkers.forEach(w=>scene.add(w.group));
// Security. Four guards on loops that skirt the reception desk and the booths: two in the
// exhibition hall, one in the foyer, one in the corridor. Their vision cones are drawn on
// the floor; a guard who sees Richie gives chase, and a guard who catches him throws him
// back to the previous checkpoint. Line of sight is a physics ray, so booths hide him.
const V=(x:number,y:number,z:number)=>new T.Vector3(x,y,z);const guards=[new Guard(900,[V(5.5,0,8),V(5.5,0,30),V(-5.5,0,30),V(-5.5,0,20)]),new Guard(901,[V(0,0,38),V(-5,0,57),V(5,0,57)]),new Guard(902,[V(-6,6,118),V(6,6,118),V(6,6,132),V(-6,6,132)]),new Guard(903,[V(-6,13,152),V(6,13,152),V(6,13,180),V(-6,13,180)])];guards.forEach(g=>scene.add(g.group));let heldBy:Guard|null=null,ejectedT=0;
const canSee=(eye:T.Vector3,target:T.Vector3)=>{const dir=target.clone().sub(eye),len=dir.length();dir.divideScalar(len);const hit=world.castRay(new R.Ray(eye,dir),len,true);return !hit||hit.collider.handle===pc.handle};
let state:'title'|'tutorial'|'cinematic'|'play'|'end'|'results'='title',paused=false,st:Stats=stats(),cp=0,charge=0,ground=false,mode:'richie'|'voxxy'|'biggy'='richie',helperCharge=0,reclines=0,crowd=0,coins=0,toastT=0,cine=0,endT=0,prevVy=0,tumble=0;
const say=(s:string,t=1.4)=>{el('toast').textContent=s;toastT=t};function reset(){const q=zones[cp];player.setTranslation({x:q[1],y:q[2]+.8,z:q[3]},true);player.setLinvel({x:0,y:0,z:0},true);player.setAngvel({x:0,y:0,z:0},true);player.setRotation({x:0,y:0,z:0,w:1},true);mode='richie';helperCharge=0;charge=0;heldBy=null;ejectedT=0;player.setGravityScale(1,true);guards.forEach(g=>g.reset())}
function play(){state='play';paused=false;for(const id of ['title','cinema','results','pause','tutorial'])el(id).hidden=true;freeLook=null;el('hud').hidden=false}
// Leaving a run: Escape pauses (touch has the MENU button), and the card resumes or drops back to
// the title. Pausing stops the physics step, so the keynote clock stops with it and no guard can
// reach Richie while the card is up.
function setPaused(on:boolean){paused=on;el('pause').hidden=!on;if(!on){charge=0;keys.delete('Space')}}
function toTitle(){state='title';paused=false;charge=0;helperCharge=0;keys.clear();freeLook=null;for(const id of ['hud','cinema','results','pause','tutorial'])el(id).hidden=true;el('title').hidden=false}
function start(){st=stats();cp=0;coins=0;crowd=0;reclines=0;crowdEx=0;finale=null;confetti.visible=false;spots.forEach(s=>{s.intensity=0;s.color.set(0xffd29b);s.target.position.x=0});robots.forEach(rb=>rb.reset());tokens.forEach(x=>x.visible=true);reset();el('title').hidden=true;el('hud').hidden=true;state='cinematic';el('cinema').hidden=false;cine=0}
function showResults(){state='results';el('hud').hidden=true;el('results').hidden=false;el('stats').innerHTML=[['TIME',fmt(st.time)],['HOPS',st.hops],['FACEPLANTS',st.faceplants],['VOXXY THROWS',st.throws],['BIGGY IMPACTS',st.impacts],['UNINTENDED STAIR DESCENTS',st.stairs],['COFFEES DESTROYED',st.coffees],['CROISSANTS DESTROYED',st.croissants],['ESCORTED OUT BY SECURITY',st.ejections],['TOKENS',coins+'/8'],['DEVELOPERS INJURED','0*']].map(x=>'<span>'+x[0]+'</span><b>'+x[1]+'</b>').join('')}
el('skip').onclick=()=>{skipReq=true};el('howto').onclick=()=>tutorial(0);setMuted(muted);for(const id of ['mute','pauseMute'])el(id).onclick=e=>{(e.currentTarget as HTMLElement).blur();setMuted(!muted)};
for(const ev of ['pointerdown','keydown'] as const)addEventListener(ev,musicStart,{once:true});
for(const [id,fn] of [['menuBtn',()=>setPaused(!paused)],['resume',()=>setPaused(false)],['quit',()=>toTitle()],['toMenu',()=>toTitle()]] as const)el(id).onclick=e=>{(e.currentTarget as HTMLElement).blur();fn()};for(const [id,fn] of [['tutNext',()=>tutNext()],['tutBack',()=>tutGo(tutI-1)],['tutSkip',()=>tutEnd(false)]] as const)el(id).onclick=e=>{(e.currentTarget as HTMLElement).blur();fn()};el('cinema').onpointerdown=()=>{skipReq=true};el('start').onclick=start;el('again').onclick=()=>{el('results').hidden=true;start()};
function step(dt:number){const p=player.translation(),v=player.linvel();const hit=world.castRay(new R.Ray(p,{x:0,y:-1,z:0}),.7,true,undefined,undefined,pc,player);const was=ground;ground=!!hit&&v.y<1.5;const q=new T.Quaternion().copy(player.rotation()),up=new T.Vector3(0,1,0).applyQuaternion(q);const pv=new T.Vector3(p.x,p.y,p.z);if(ground&&!was&&Math.abs(prevVy)>4){if(up.y<.65)st.faceplants++;say(Math.abs(prevVy)>12?'RICHIE DISAGREES':'BONK',.7);robots.forEach(rb=>{if(rb.position.distanceTo(pv)<9)rb.react()})}if(ground&&up.y<.96){tumble+=dt;if(tumble>1){player.setRotation(q.slerp(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),yaw),dt*8),true);player.setAngvel({x:0,y:0,z:0},true)}}else tumble=0;
 const f=new T.Vector3(-Math.sin(yaw),0,Math.cos(yaw)),r=new T.Vector3(-Math.cos(yaw),0,-Math.sin(yaw));const dir=f.multiplyScalar((keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-stick.y).add(r.multiplyScalar((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+stick.x)).clampLength(0,1);
 if(press.has('KeyR')){reset();say('RETRY-DRIVEN DEVELOPMENT')}if(mode==='richie'&&!heldBy){if(keys.has('Space')&&ground)charge=Math.min(1,charge+dt);if(release.has('Space')&&ground){const c=Math.max(.08,charge);player.setLinvel({x:dir.x*(2.5+c*5),y:4.5+c*5.5,z:dir.z*(2.5+c*5)},true);player.setAngvel({x:dir.z*1.5,y:.2,z:-dir.x*1.5},true);st.hops++;tone(180,580);charge=0;headKick=true}if(!ground&&dir.lengthSq())player.applyImpulse({x:dir.x*dt,z:dir.z*dt,y:0},true)}
 if(press.has('KeyE')){if(mode!=='richie'){mode='richie'}else if(p.z>57&&p.z<68){mode='voxxy';voxxy.busy=true;player.setGravityScale(0,true);say('VOXXY CAN HELP')}else if(p.z>118&&p.z<136){mode='biggy';biggy.busy=true;biggy.place(0,6,127,0);helperCharge=0;player.setTranslation({x:0,y:7,z:132},true);say('HIT RICHIE VERY HARD')}else if(Math.abs(p.z-207)<5){reclines++;say(reclines%3?'RECLINE. …NOTHING.':'EJECT MODE');droid.react();if(reclines%3===0)player.setLinvel(ballistic(p,{x:0,y:rowY(7)+1,z:221},1.45),true)}}
 if(mode==='voxxy'){const vp=voxxy.position;player.setTranslation({x:vp.x,y:vp.y+2.3,z:vp.z},true);player.setLinvel({x:0,y:0,z:0},true);if(keys.has('Space'))helperCharge=Math.min(1,helperCharge+dt);if(release.has('Space')){player.setGravityScale(1,true);voxxy.busy=false;voxxy.react();player.setLinvel(ballistic(player.translation(),{x:dir.x*4,y:1,z:85+helperCharge*2},1.55),true);mode='richie';st.throws++;headKick=true;tone(140,700,.45,'sawtooth');say('THE TITLE WAS A SUGGESTION');helperCharge=0}}
 if(mode==='biggy'){if(keys.has('Space')){helperCharge=Math.min(1,helperCharge+dt);biggy.place(0,6,127-helperCharge*4,0)}if(release.has('Space')){biggy.place(0,6,130.6,0);biggy.react();biggyBusyT=1.5;player.setLinvel(ballistic(p,{x:dir.x*5,y:14,z:152+helperCharge*4},1.8),true);st.impacts++;mode='richie';headKick=true;tone(85,22,.6,'sawtooth');say(helperCharge>.8?'ORBIT ACHIEVED':'THIS SEEMS UNSAFE');helperCharge=0}}
 // Riding one: while Richie is on the treads the steps carry him up the slope. The carry moves
 // him rather than pushing him — a velocity along a ramp he is resting on is inside the contact's
 // friction cone, so the solver cancelled it every step and he stood there. Displacement is
 // parallel to the surface, so it never drives him into it. A hop still leaves the escalator,
 // because the carry needs contact.
 if(ground&&p.y<7&&p.z>89.5&&p.z<114.3)for(const s of [-1,1])if(Math.abs(p.x-s*8.4)<1.25){player.setTranslation({x:p.x,y:p.y+ESC_Y*dt,z:p.z+ESC_Z*dt},true);break}
 world.step();prevVy=v.y;const np=player.translation();ejectedT=Math.max(0,ejectedT-dt);if(ejectedT<=0)for(let i=cp+1;i<zones.length;i++){const z=zones[i];if(np.z>=z[3]&&np.y>=z[2]-.5){cp=i;say('CHECKPOINT · '+z[0])}}tokens.forEach((x,i)=>{x.rotation.y+=dt*2;if(x.visible&&x.position.distanceTo(new T.Vector3().copy(np))<1.2){x.visible=false;coins++;say('EXTREMELY NECESSARY TOKEN')}});if(np.z>226&&np.y<12&&np.y>5.5&&crowd<3){const target=crowd===2?{x:0,y:8.6,z:256}:{x:(crowd%2?1:-1)*1.5,y:crowd?8:rowY(10)+1.6,z:233+crowd*8};player.setLinvel(ballistic(np,target,crowd===2?2:1.3),true);crowd++;crowdEx=1;say(crowd===3?'ONE LAST BAD IDEA':'AUDIENCE PARTICIPATION')}if(state==='play'&&np.z>250&&np.y<10&&crowd===3){state='end';crowdEx=2;endT=0;say('WHAM');spots.forEach(s=>s.intensity=80);
  // Grand finale: the whole expedition joins Richie on stage, from the wings and from behind the screen.
  finale=new T.Vector3(T.MathUtils.clamp(np.x,-5,5),6.9,T.MathUtils.clamp(np.z,251,261));voxxy.celebrate([-12,6.9,257],finale);droid.celebrate([12,6.9,255],finale);biggy.celebrate([12.5,6.9,266],finale);confetti.visible=true}
 // At the party Richie bounces too, antennas up, every second or so.
 if(state==='end'&&ground&&Math.floor(st.time*.9)!==Math.floor((st.time-dt)*.9)){player.setLinvel({x:(Math.random()-.5)*1.5,y:5.2,z:(Math.random()-.5)*1.5},true);player.setAngvel({x:0,y:(Math.random()-.5)*3,z:0},true);headKick=true}if(np.y<(cp>4?4.5:-8)||Math.abs(np.x)>25)reset();st.time+=dt}
// Light grading by where the camera is: a bright exhibition hall, a warm foyer, a dim corridor, a dark room with a lit stage.
const GRADES=[{to:112,h:1.5,s:2.6,c:0xfff0dc,f:0x0b1118},{to:147,h:1.0,s:2.1,c:0xffcf9c,f:0x120c08},{to:186,h:.8,s:1.6,c:0xd4dcff,f:0x06080f},{to:1e9,h:.62,s:1.45,c:0xccd6ff,f:0x030408}].map(g=>({...g,c:new T.Color(g.c),f:new T.Color(g.f)}));
function grade(d:number){const g=GRADES.find(g=>camera.position.z<g.to)!,k=Math.min(1,d*2.5);hemi.intensity+=(g.h-hemi.intensity)*k;sun.intensity+=(g.s-sun.intensity)*k;sun.color.lerp(g.c,k);fog.color.lerp(g.f,k);sky.copy(fog.color)}
// Bloom makes the light fittings, lightboxes and robot eyes read as sources. Touch devices and ?nofx skip it.
const fx=!touch&&!new URLSearchParams(location.search).has('nofx');let composer:EffectComposer|null=null;if(fx){composer=new EffectComposer(renderer,new T.WebGLRenderTarget(innerWidth,innerHeight,{type:T.HalfFloatType,samples:4}));composer.setPixelRatio(renderer.getPixelRatio());composer.setSize(innerWidth,innerHeight);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.3,.55,1.25));composer.addPass(new OutputPass())}
// The briefing behind HOW THIS WORKS (words in tutorial.ts). Every card is shot live: the venue keeps
// running underneath, the camera sits on whoever the card is about, and on his own card Richie demonstrates.
const deck=cards(touch?'HOP':'SPACE',touch),tutPos=new T.Vector3(),tutAt=new T.Vector3(),tutLook=new T.Vector3(),tutFace=new T.Quaternion();let tutI=0,tutT=0,tutCut=true,tutHopped=false;
function tutGo(i:number){tutI=T.MathUtils.clamp(i,0,deck.length-1);tutT=0;tutCut=true;/* on his own card Richie turns to face the camera, the hall behind him */player.setRotation(tutFace.setFromAxisAngle(new T.Vector3(0,1,0),deck[tutI].focus==='richie'?Math.PI:0),true);const c=deck[tutI],two=(n:number)=>String(n).padStart(2,'0');el('tutTag').textContent=two(tutI+1)+' / '+two(deck.length)+' · '+c.tag;el('tutTitle').textContent=c.title;el('tutBody').innerHTML=c.body;el('tutKeys').innerHTML=c.keys.map(([k,v])=>`<span><kbd>${k}</kbd> ${v}</span>`).join('');el('tutArt').innerHTML=(c.art??[]).map(n=>[n,texUrl(n)]).filter(x=>x[1]).map(([n,u])=>`<img src="${u}" alt="${n}"${n==='duke'?' class="cut"':''}>`).join('');el('tutBack').hidden=tutI===0;el('tutNext').textContent=tutI===deck.length-1?'LET’S MAKE THIS WORSE ↗':'NEXT →';el('tutDots').innerHTML=deck.map((_,n)=>`<i${n===tutI?' class="on"':''}></i>`).join('');({voxxy,biggy,droid} as Record<string,Robot>)[c.focus]?.react();const card=el('tutCard');card.classList.remove('in');void card.offsetWidth;card.classList.add('in')}
function tutorial(i=0){cp=0;reset();state='tutorial';freeLook=null;for(const id of ['title','hud','cinema','results'])el(id).hidden=true;el('tutorial').hidden=false;tutGo(i)}
function tutEnd(toGame:boolean){el('tutorial').hidden=true;charge=0;press.clear();if(toGame)start();else{state='title';el('title').hidden=false}}
const tutNext=()=>tutI===deck.length-1?tutEnd(true):tutGo(tutI+1);
// Physics runs during the briefing so Richie sits on the floor, and on his card he shows the move: the head sinks
// through a charge, he hops, lands badly, and is helped upright, over and over, a metre either side of his mark.
function tutTick(dt:number){tutT+=dt;const demo=deck[tutI].focus==='richie',ph=tutT%2.8;charge=demo&&ph>1.1&&ph<2.2?(ph-1.1)/1.1:0;if(ph<1){tutHopped=false;player.setRotation(new T.Quaternion().copy(player.rotation()).slerp(tutFace,Math.min(1,dt*5)),true)}if(demo&&ph>=2.2&&!tutHopped){tutHopped=true;const s=Math.floor(tutT/2.8)%2?-1:1;player.setLinvel({x:s*1.5,y:8.4,z:0},true);player.setAngvel({x:.4,y:.2,z:-s*.9},true);headKick=true;tone(180,580)}world.step()}
// Where the camera wants to be for this card. In landscape the subject is pushed right of centre, clear of the text.
function tutShot(){const f=deck[tutI].focus,orbit=(q:T.Vector3,yaw:number,d:number,h:number,lift:number,a=.6)=>{tutPos.set(q.x+Math.sin(yaw+a)*d,q.y+h+lift,q.z+Math.cos(yaw+a)*d);tutAt.set(q.x,q.y+h,q.z)};
 if(f==='story'){tutPos.set(4.4,2.8,-2.6);tutAt.set(0,1.4,9)}else if(f==='richie'){tutPos.set(1.7,1.25,.7);tutAt.set(0,.9,4)}
 else if(f==='voxxy')orbit(voxxy.position,voxxy.group.rotation.y,4.4,1.15,.5)
 else if(f==='biggy')orbit(biggy.position,biggy.group.rotation.y,5.6,1.35,.6)
 else if(f==='droid')orbit(droid.position,droid.group.rotation.y,6.8,2.5,.4)
 else if(f==='expo'){tutPos.set(.8,2.1,30.2);tutAt.set(8.4,1.65,34.4)}
 else if(f==='guard'){const g=guards[0].group,y=g.rotation.y;tutPos.set(g.position.x+Math.sin(y+2.6)*7.5,g.position.y+5.8,g.position.z+Math.cos(y+2.6)*7.5);tutAt.set(g.position.x+Math.sin(y)*3.2,g.position.y+.4,g.position.z+Math.cos(y)*3.2)}
 else{tutPos.set(7.5,13,221);tutAt.set(0,8.2,252)}
 if(innerWidth>innerHeight*1.15){const dx=tutAt.x-tutPos.x,dz=tutAt.z-tutPos.z,l=Math.hypot(dx,dz)||1;tutAt.x-=-dz/l*l*.34;tutAt.z-=dx/l*l*.34}}
let last=performance.now(),acc=0,frames=0;function loop(now:number){requestAnimationFrame(loop);const d=T.MathUtils.clamp((now-last)/1000,0,.2);last=now;/* the first rAF timestamp can precede the performance.now() taken during module evaluation, and a negative step would run every decay backwards */if((state==='play'||state==='end')&&!paused){acc+=d;let n=0;while(acc>=DT&&n++<12){step(DT);acc-=DT}}else if(state==='tutorial'){acc+=d;let n=0;while(acc>=DT&&n++<12){tutTick(DT);acc-=DT}}const p=new T.Vector3().copy(player.translation());richie.position.copy(p);richie.quaternion.copy(player.rotation());sun.target.position.copy(p);
 // The venue lives whatever the state: robots patrol, people wander, the front rows bounce.
 const tt=now*.001;escalatorTick(d);robots.forEach(rb=>rb.update(d,tt,p));walkers.forEach(w=>w.update(d,tt));crowdM.update(tt,crowdEx);crowdEx=Math.max(0,crowdEx-d*.4);if(biggyBusyT>0){biggyBusyT-=d;if(biggyBusyT<=0)biggy.busy=false}
 const catchable=state==='play'&&!paused&&mode==='richie'&&!heldBy;guards.forEach(g=>{const ev=g.update(d,tt,{pos:p,catchable,canSee});
  if(ev==='spotted'){say('HEY! NO ROBOTS!',1);tone(620,880,.12,'square')}
  else if(ev==='grabbed'){heldBy=g;player.setGravityScale(0,true);player.setLinvel({x:0,y:0,z:0},true);player.setAngvel({x:0,y:0,z:0},true);say('CAUGHT.',1)}
  else if(ev==='thrown'&&heldBy===g){heldBy=null;player.setGravityScale(1,true);const back=zones[Math.max(0,cp-1)],from=player.translation(),dist=Math.hypot(back[1]-from.x,back[3]-from.z);player.setLinvel(ballistic(from,{x:back[1],y:back[2]+1.5,z:back[3]},T.MathUtils.clamp(dist/16,1.2,2.6)),true);player.setAngvel({x:-3,y:1,z:0},true);cp=Math.max(0,cp-1);ejectedT=3;st.ejections++;headKick=true;tone(300,90,.5,'sawtooth');say('ESCORTED OUT',1.8)}
  else if(ev==='lost')say('…HMPF.',.8)});
 if(heldBy){const h=heldBy.hands;player.setTranslation({x:h.x,y:h.y,z:h.z},true);player.setLinvel({x:0,y:0,z:0},true);player.setRotation({x:0,y:0,z:0,w:1},true)}
 // Antennas are springs: a landing or launch sets them ringing, and the finale is a celebration.
 const vy=player.linvel().y;wobble=Math.min(1.2,wobble*Math.pow(.15,d)+Math.abs(vy-lastVy)*.08);lastVy=vy;const t=now*.001,ring=(state==='end'||state==='results'?.55*Math.sin(t*9):Math.sin(t*16)*wobble)+(state==='title'?Math.sin(t*2.2)*.1:0);antennaL.rotation.z=ring;antennaR.rotation.z=-ring;richieHead.rotation.x=T.MathUtils.clamp(-vy*.03,-.25,.25)*(state==='play'?1:0);
 {const pressed=(state==='play'&&keys.has('Space'))||(state==='tutorial'&&charge>0),target=pressed?-(.25+.75*Math.max(charge,helperCharge))*HEAD_DIP:0;if(headKick){headV+=1.3;headKick=false}
  for(let n=Math.ceil(d/.02),h=d/n,i=0;i<n;i++){headV+=((target-headY)*90-headV*9)*h;headY+=headV*h;if(headY>HEAD_POP){headY=HEAD_POP;headV=Math.min(headV,0)}if(headY<-HEAD_DIP){headY=-HEAD_DIP;headV=Math.max(headV,0)}}
  richieHead.position.y=headBase+headY}sun.position.copy(p).add(new T.Vector3(-10,20,-10));if(state==='title'){const t=now*.001;richie.position.set(2,2+Math.abs(Math.sin(t))*1.2,4);richie.scale.setScalar(2);richie.rotation.y=Math.PI+t*.2;camera.position.set(5,4,-7);camera.lookAt(0,2,4)}else richie.scale.setScalar(1);
 if(press.has('KeyM'))setMuted(!muted);
 if(press.has('Escape')&&state!=='tutorial'){if(state==='play'||state==='end')setPaused(!paused);else if(state==='cinematic'||state==='results')toTitle()}
 if(state==='tutorial'){tutShot();if(tutCut){camera.position.copy(tutPos);tutLook.copy(tutAt);tutCut=false}else{camera.position.lerp(tutPos,Math.min(1,d*2));tutLook.lerp(tutAt,Math.min(1,d*3))}camera.lookAt(tutLook);if(press.has('Escape'))tutEnd(false);else if(press.has('ArrowLeft'))tutGo(tutI-1);else if(press.has('ArrowRight')||press.has('Enter')||press.has('Space'))tutNext()}
 if(state==='cinematic'){cine+=d;const shots=[['KINEPOLIS · ANTWERP',new T.Vector3(8,9,-20),new T.Vector3(0,4,-5)],['DEVOXX BELGIUM',new T.Vector3(-7,5,25),new T.Vector3(0,2,52)],['THE KEYNOTE IS UPSTAIRS.',new T.Vector3(7,10,109),new T.Vector3(0,7,126)],['KEYNOTE STARTS IN 10:00',new T.Vector3(0,16,198),new T.Vector3(0,8,262)],['ONE SMALL PROBLEM.',new T.Vector3(2,2,0),new T.Vector3(0,.8,4)],['RICHIE HAS NO LEGS.',new T.Vector3(1,1,1),new T.Vector3(0,.2,4)],['PLEASE DO NOT THROW RICHIE',new T.Vector3(2,1,0),new T.Vector3(0,1,4)]] as const;const i=Math.min(6,Math.floor(cine/2.6));el('cinemaText').textContent=shots[i][0];camera.position.lerp(shots[i][1],.08);camera.lookAt(shots[i][2]);if(cine>18||skipReq||press.has('Space')||press.has('Enter')||press.has('KeyE')){skipReq=false;play()}}
 else if(state==='play'){if(freeLook){camera.position.copy(freeLook.pos);camera.lookAt(freeLook.at)}else{camera.position.lerp(camTarget(p),.12);camera.lookAt(p.x,p.y+.7,p.z)}}
 if(state==='end'||state==='results'){const was=endT;endT+=d;crowdEx=1.5;updateConfetti(d,tt);spots.forEach((s,i)=>{s.intensity=90;s.target.position.x=Math.sin(tt*1.1+i*Math.PI)*7;s.color.setHSL(((tt*.12)+i*.5)%1,.75,.6)});
  const c=finale??new T.Vector3(0,6.9,256),a=Math.sin(endT*.28)*.9;camera.position.lerp(new T.Vector3(c.x+Math.sin(a)*13,c.y+5,c.z-Math.cos(a)*13),.06);camera.lookAt(c.x,c.y+1.2,c.z);
  if(state==='end'){if(was<2&&endT>=2)say('ROBOTS ASSEMBLE',1.6);if(was<5.5&&endT>=5.5)say('KEYNOTE READY.',2);if(endT>9)showResults()}}
 if(state==='play'){el('zone').textContent=String(cp+1).padStart(2,'0')+' / '+zones[cp][0];el('time').textContent=st.time>600?'FASHIONABLY LATE':fmt(600-st.time);el('tokens').textContent=coins+' / 8 TOKENS';el('bar').style.width=(Math.max(charge,helperCharge)*100)+'%';const pp=player.translation();const HK=touch?'HOP':'SPACE';el('hint').textContent=heldBy?'CAUGHT. THIS IS FINE.':guards.some(g=>g.state==='alert'||g.state==='chase')?'SECURITY · RUN':mode==='voxxy'?`VOXXY · HOLD ${HK} TO THROW`:mode==='biggy'?`BIGGY · HOLD ${HK} FOR MAXIMUM CHAOS`:pp.z>57&&pp.z<68?'E · VOXXY CAN HELP':pp.z>118&&pp.z<136?'E · ASK BIGGY':Math.abs(pp.z-207)<5?'E · DROID: RECLINE':touch?'HOLD HOP TO CHARGE':'SPACE TO HOP';toastT-=d;if(toastT<=0)el('toast').textContent=''}press.clear();release.clear();musicTick(d);grade(d);if(composer)composer.render(d);else renderer.render(scene,camera);document.getElementById('boot')?.remove()}
function camTarget(p:T.Vector3){const off=new T.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)).multiplyScalar(dist+Math.min(8,player.linvel().y>8?5:0));return p.clone().add(new T.Vector3(0,.7,0)).add(off)}
function fmt(s:number){return Math.floor(Math.max(0,s)/60).toString().padStart(2,'0')+':'+Math.floor(Math.max(0,s)%60).toString().padStart(2,'0')}
// Debug hook. The release screenshots drive the game through this rather than by
// synthesising input against a physics simulation, so the captures are deterministic.
// See scripts/screenshots.mjs.
(globalThis as any).__richie={get state(){return state},get music(){return {muted,playing:!music.paused,t:+music.currentTime.toFixed(1),vol:+music.volume.toFixed(2)}},get ground(){return ground},get keys(){return [...keys]},get head(){return headY},get zone(){return cp},get mode(){return mode},get stats(){return st},
 start(skipIntro=true){start();if(skipIntro&&state==='cinematic')play()},
 tutorial(i=0){tutorial(i);return deck[tutI].title},
 get paused(){return paused},
 pause(on=true){setPaused(on)},
 menu(){toTitle()},
 cinematic(shot=0){start();state='cinematic';el('cinema').hidden=false;cine=shot*2.6},
 place(x:number,y:number,z:number){play();player.setTranslation({x,y,z},true);player.setLinvel({x:0,y:0,z:0},true);player.setAngvel({x:0,y:0,z:0},true)},
 warp(i:number){cp=Math.round(T.MathUtils.clamp(i,0,zones.length-1));reset();play();return zones[cp][0]},
 hop(c=1){player.setLinvel({x:0,y:4.5+c*5.5,z:2.5+c*5},true);player.setAngvel({x:1.5,y:.2,z:0},true);st.hops++;charge=0;headKick=true},
 charging(c=1){charge=T.MathUtils.clamp(c,0,1)},
 look(px:number,py:number,pz:number,ax:number,ay:number,az:number){freeLook={pos:new T.Vector3(px,py,pz),at:new T.Vector3(ax,ay,az)}},
 camera(y=0,p=.42,d=8){freeLook=null;yaw=y;pitch=p;dist=d;const t=new T.Vector3().copy(player.translation());camera.position.copy(camTarget(t));camera.lookAt(t.x,t.y+.7,t.z)},
 set(o:{tokens?:number,stats?:Partial<Stats>}){if(o.tokens!==undefined){const n=o.tokens;coins=n;tokens.forEach((x,i)=>x.visible=i>=n)}if(o.stats)Object.assign(st,o.stats)},
 results(){showResults()},
 finale(){play();crowd=3;cp=7;player.setTranslation({x:0,y:8.2,z:255},true);player.setLinvel({x:0,y:0,z:0},true)},
 get crowd(){return {ex:+crowdEx.toFixed(2),clusters:crowdM.group.children.map(m=>m.visible?1:0)}},
 get guards(){return guards.map(g=>[g.state,+g.group.position.x.toFixed(1),+g.group.position.z.toFixed(1)])},
 alarm(){play();cp=1;reset();guards[1].place(0,0,37,Math.PI)},
 robotView(i=0,d=4,h=1.4,side=.5){const rb=robots[i],y=rb.group.rotation.y,q=rb.position;freeLook={pos:new T.Vector3(q.x+Math.sin(y+side)*d,q.y+h+.6,q.z+Math.cos(y+side)*d),at:new T.Vector3(q.x,q.y+h,q.z)}},
 get robots(){return robots.slice(0,3).map(rb=>[+rb.position.x.toFixed(1),+rb.position.y.toFixed(1),+rb.position.z.toFixed(1)])},
 pose(){const t=player.translation();return{x:t.x,y:t.y,z:t.z,zone:cp,state}}};
if(import.meta.env.DEV)(globalThis as any).__scene=scene;
requestAnimationFrame(loop);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer?.setSize(innerWidth,innerHeight)});
